### PR TITLE
Update `uaa-ci` repo approvers and other repo team members

### PR DESCRIPTION
**Pull request by hsinn0**
- Made SAP team approvers of `uaa-ci` repo so they can create PRs for the private repo. After that, we do not need separate `area` for `uaa-ci` repo, so removed the `area` that was created specifically for `uaa-ci`.
- Updated VMware team members.

### CODE REVIEW

**Review by beyhan — COMMENTED** [review]
Hi @hsinn0,

Bruce Ricard, Danny Faught and Alicia Yingling get removed as approver. Usually, we need their thumps up in this case as approval or mentioning via comment in the PR and two week wait time for revocation. In case we need to wait two weeks I would propose to split the pr so that the move of the  `uaa-ci` repository to a different area is not blocked.

**Comment by hsinn0** [comment]
> Bruce Ricard, Danny Faught and Alicia Yingling get removed as approver.

They have not been with the company for more than a few weeks.

**Comment by beyhan** [comment]
FYI @swalchemist, @Tallicia, @bruce-ricard

**Review by rkoster — APPROVED** [review]

**Comment by beyhan** [comment]
Merging since two weeks are over.

**Review by beyhan — APPROVED** [review]

**Pull request merged**
