### PR TITLE
Add `geigerj0` to approvers of `Autoscaler`

### PR DESCRIPTION
**Pull request by geigerj0**
I am part of an internal SAP team which is heavily involved in the development of [`cloudfoundry/app-autoscaler-release`](https://github.com/cloudfoundry/app-autoscaler-release). 

Here are my contributions throughout the `cloudfoundry` organization (assembled with [`./toc/working-groups/contributions-for-user.sh`](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/contributions-for-user.sh)

| Working Group                | Area                            | Contributions                                                       |
|------------------------------|---------------------------------|---------------------------------------------------------------------|
| App Runtime Interfaces       | Autoscaler                      | https://gist.github.com/geigerj0/d3eb1339814146e60de695066ccd3725   |
| App Runtime Platform         | Diego                           | https://gist.github.com/geigerj0/7379027882eb391868854030d61a995e   |
| App Runtime Platform         | Networking                      | https://gist.github.com/geigerj0/e8c1aef52915936ddea8c231188a67b9   |
| Documentation                | Docs                            | https://gist.github.com/geigerj0/6d57e60566aebf11831641a287288c95   |
| Foundational Infrastructure  | Credential Management (Credhub) | https://gist.github.com/geigerj0/6d57e60566aebf11831641a287288c95   |

### CODE REVIEW

**Review by silvestre — APPROVED** [review]

**Review by joergdw — APPROVED** [review]

**Comment by beyhan** [comment]
This is now in your hands @gerg or @stephanme :-)

**Review by stephanme — APPROVED** [review]
You have the contributions and two +1 votes by WG area approvers.
You became Reviewer ~ 1 month ago (#744) whereas ["Requirements for an Approver"](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#approver) asks for "Reviewer of the codebase for at least 3 months.

Since I know the team setup and you got @silvestre 's +1, I approve as well.
If @Gerg doesn't object, I merge this PR end of this week.

**Comment by stephanme** [comment]
@geigerj0 : Can you rebase the PR and resolve the conflict?

**Comment by geigerj0** [comment]
> @geigerj0 : Can you rebase the PR and resolve the conflict?

@stephanme done

**Comment by stephanme** [comment]
Welcome as Approver in the ARI working group.

**Pull request merged**
