### PR TITLE
Adding gm2552 as BOSH and Stemcell reviewer.

### PR DESCRIPTION
**Pull request by gm2552**

### CODE REVIEW

**Review by rkoster — APPROVED** [review]

**Review by rkoster — CHANGES_REQUESTED** [review]
@gm2552 could you try and fix Easy CLA

**Comment by rkoster** [comment]
Please make sure to follow: https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address so your commit can be linked to your github profile.

**Comment by gm2552** [comment]
> @gm2552 could you try and fix Easy CLA

I've submitted a ticket to get this resolved.

**Comment by gm2552** [comment]
Closing out and resubmitting PR with proper email address.

**Pull request closed without merging**
