### PR TITLE
[ARI] Add @johha to ARI CAPI teams

### PR DESCRIPTION
**Pull request by Gerg**
Follow up to [#329]

### CODE REVIEW

**Comment by Gerg** [comment]
Okay, I'll close this PR. Feel free re-open if the automation isn't sufficient.

**Comment by sethboyles** [comment]
I don't think this worked, as @johha has not been added to the CAPI maintainers list: 

https://github.com/cloudfoundry/community/blob/3f3b19a0efbb21467490314840a2253accdda825/org/cloudfoundry.yml#L2466-L2480

**Comment by Gerg** [comment]
Any ideas @stephanme?

**Comment by stephanme** [comment]
The github team [App Runtime Interfaces WG CAPI](https://github.com/orgs/cloudfoundry/teams/app-runtime-interfaces-wg-capi) is one of the deprecated, non-standard teams that will be deleted by #262 (probably already next week).

The standard github team for CAPI approvers according to [rfc-0005-github-teams-and-access.md](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0005-github-teams-and-access.md) is [wg-app-runtime-interfaces-capi-approvers](https://github.com/orgs/cloudfoundry/teams/wg-app-runtime-interfaces-capi-approvers). This team is generated from the WG charter.

wg-app-runtime-interfaces-capi-approvers is already used for controlling access to the CAPI repos including branch protection rules (in addition to the non-standard teams until #262 is accepted). However, the old team 'App Runtime Interfaces WG CAPI' might still be used outside of github, e.g. for Concourse authorisation. I suggest to switch over to wg-app-runtime-interfaces-capi-approvers.

@sethboyles , @gerg : Can you review the capi approvers in the [WG charter](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/app-runtime-interfaces.md)? At least Jen seems not correct anymore (left the cloudfoundry org).

**Comment by stephanme** [comment]
I forgot: @johha has write access to the CAPI repos. But he could not trigger a CAPI release. This is currently discussed in https://cloudfoundry.slack.com/archives/C07C04W4Q/p1659451587280529

So I think we can close this PR again.

**Pull request closed without merging**
