### PR TITLE
remove identity-ci

### PR DESCRIPTION
**Pull request by bruce-ricard**
We moved this repo in the pivotal org here: https://github.com/pivotal/uaa-ci as it is a private repo containing private information.

The whole repo can be deleted.

### CODE REVIEW

**Review by rkoster — APPROVED** [review]

**Review by rkoster — CHANGES_REQUESTED** [review]
@bruce-ricard could you update the PR to add `archive: true` instead of removing the repo from the list?

**Comment by bruce-ricard** [comment]
I don't really want to archive it though, because we are not archiving it, we are moving it.

It feels odd to copy it to another org, and archive it here.

But I'll do it if that's what you want. Let me know.

**Comment by rkoster** [comment]
It's about intellectual property being moved out of a foundation-owned GitHub org, which is why it's better to archive the repo and update the Readme with a link to the new location.

**Comment by beyhan** [comment]
Closing in favour of https://github.com/cloudfoundry/community/pull/697

**Pull request closed without merging**
