### PR TITLE
Change from loewenstein to loewenstein-sap

### PR DESCRIPTION
**Pull request by loewenstein-sap**

### CODE REVIEW

**Comment by loewenstein** [comment]
I confirm, that @loewenstein-sap is my new handle for SAP SE related use on github.com.

**Comment by beyhan** [comment]
I think this is a WG related topic. If @ForestEckhardt or @dmikusa and @ameowlia could approve the pr we are good to go.

**Review by dmikusa — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Comment by loewenstein** [comment]
@cloudfoundry/toc do we need any further approvals?

**Comment by beyhan** [comment]
I'm waiting for an approval from @ameowlia because it is a change in the ARP WG but nothing from the TOC side.

**Review by ameowlia — APPROVED** [review]

**Pull request merged**
