### PR TITLE
RFC: Project Roadmap + Visibility

### PR DESCRIPTION
**Pull request by geofffranks**
- Everyone is welcome to review and comment.
- We will discuss this in the TOC meeting today (Nov 9th).
- In the TOC meeting next week the TOC members will vote on whether to accept this working agreement.

### CODE REVIEW

**Comment by beyhan** [comment]
I like the proposal. One point, which is not clear and I would like to see is an easy way to discover old proposals. It doesn't look so straight forward to find old cards in a Github project. Filtering on `closed` cards and using the free text search delivers interesting results :-).

**Review by LeePorte — APPROVED** [review]

**Review by stephanme — APPROVED** [review]

**Review by loewenstein — APPROVED** [review]
Not sure if Terraform adds or removes complexity of this process, in particular when expcting that the new Github projects (currently in beta) does or will solve parts of those issues.

I'll still approve, as this will be managed by individual working groups and on an opt-in scheme.

**Review by dsboulder — APPROVED** [review]

**Comment by geofffranks** [comment]
@cloudfoundry/toc this has been updated for the new RFC format

**Review by emalm — APPROVED** [review]

**Comment by emalm** [comment]
Merging, as this has unanimous approval from the TOC. Will try out my latest changes to the numbering script after merging.

**Pull request merged**
