### PR TITLE
Add ARI RFC for Moving Buildpack Dependency Repositories to CFF AWS Accounts

### PR DESCRIPTION
**Pull request by Gerg**
Previous draft version in [this google doc](https://docs.google.com/document/d/1ElGwXudHUxzUuCBEkG8UXzI1YxqIq_eYJzrHw8PAPI4/edit#).

Rendered version of the RFC: https://github.com/cloudfoundry/community/blob/rfc-move-buildpacks-dependencies-to-cff/toc/rfc/app-runtime-interfaces/rfc-draft-move-buildpacks-dependencies-to-cff.md

### CODE REVIEW

**Comment by Gerg** [comment]
FYI @dmikusa-pivotal @pivotal-david-osullivan @arjun024 @brayanhenao

**Comment by LeePorte** [comment]
@christopherclark is is possible to contact our AWS TAM to ask about transferring large buckets between accounts?

**Comment by Gerg** [comment]
@LeePorte From their support site:
> Warning: AWS Support can't transfer bucket ownership or copy Amazon S3 objects or manipulate any configuration options in AWS accounts. Also, you can't separate an AWS account from an Amazon.com account.

Source: https://aws.amazon.com/premiumsupport/knowledge-center/account-transfer-s3/

**Comment by Gerg** [comment]
Other ideas we discussed in this weeks TOC meeting:

1. Moving over the s3 buckets in addition to the CloudFront distributions
    - Probably too expensive with current bucket sizes
    - Maybe we can consider as a follow-up project if we can reduce bucket sizes
1. Deleting old dependencies to reduce bucket sizes
    - Buildpacks don't have a deprecation policy for this currently
    - If buildpacks WG had more direct access to the download statistics, making decisions like this might be easier
1. Re-architect buildpacks to remove centralized dependency cache
1. Move dependency cache to github asset storage instead of AWS
1. Worst case, VMware can fall back on working with the Linux Foundation to manually renew the certificates 
    - This is a bit risky long-term, since it involves a repeated manual process every year

**Comment by Gerg** [comment]
@cloudfoundry/toc I motion to commence the Final Comment Period

**Comment by emalm** [comment]
@Gerg Do we have an estimate on what the CloudFront costs are per month?

You also mention in the "cons" section that there could be some unforeseen issues in using CloudFront and S3 across 2 different AWS accounts: is there a plan to discover and mitigate those potential issues?

**Comment by emalm** [comment]
Note from TOC meeting discussion on 2022-06-07: let's document that we'll try setting up CloudFront for this in the CFF account and monitor the cost when we switch over, and if it's more expensive than expected we'll switch it back to the VMware account until we figure something out.

**Comment by Gerg** [comment]
> an estimate on what the CloudFront costs are per month?

I wasn't able to get a detailed breakdown from the team currently operating those CloudFront distributions, but they said the current cost for all CloudFront distributions on that account is ~$10k/mo.

**Comment by Gerg** [comment]
@cloudfoundry/toc This issue has kind of stalled out. What are the next steps to getting it approved?

**Comment by emalm** [comment]
@Gerg We had already said in https://github.com/cloudfoundry/community/pull/279#issuecomment-1154554921 that we're ok trying this out, but we'd like to document in the RFC text that we'll monitor the cost over some period of time after the CloudFront switchover and if it is more expensive than expected we'll switch it back to evaluate other options. Could you please update the proposal to that effect? Thanks!

**Comment by Gerg** [comment]
@cloudfoundry/toc  I updated the RFC to incorporate your feedback. Please let me know if you would like any additional changes. Otherwise, I motion to commence the Final Comment Period.

**Comment by AP-Hunt** [comment]
@Gerg TOC agrees. We start the final comment period. Ends 26 July.

**Review by stephanme — APPROVED** [review]

**Review by emalm — APPROVED** [review]

**Pull request merged**
