### PR TITLE
Add Ajayan Borys to list of Docs approvers

### PR DESCRIPTION
**Pull request by HenryBorys**
@ameowlia Hi. I'm a Tech Writer at VMware and just joined our CloudFoundry docs team. Thanks for your help!

### CODE REVIEW

**Review by ameowlia — APPROVED** [review]
LGTM

**Comment by HenryBorys** [comment]
I have successfully gone through the Easy CLA authorization. Not sure why it still shows as missing.

**Review by Gerg — APPROVED** [review]
I approve, contingent on the CLA issue resolving.

**Review by rkoster — CHANGES_REQUESTED** [review]
Would it be possible to provide links to contributions made to satisfy the reviewer role requirements outlined here: https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#requirements-2

**Comment by ameowlia** [comment]
@rkoster, informally, I have been holding a different standard for new approvers for SWE v docs for the following reasons:

* The reviewer requirements were written with software engineers in mind, not docs contributors.
* The docs repos are separate from code repos.
* Our docs teams have been extremely understaffed recently and are only recently beginning to be staffed.
* Given their extreme understaffed-ness, there exist very few people who can approve PRs. Until recently, the number was practically 0 for several areas (there were people listed but they were no longer actually contributing).
* Ultimately it is up to the WG leads to nominate an approver.

For those reasons I am happy to approve @HenryBorys's addition. 

In the future we could...
* Document an official different process for docs members. 
* Do nothing and keep handling them as one offs. 

@rkoster, @Gerg -  I'm curious to hear your thoughts on the matter.

**Review by rkoster — APPROVED** [review]
@ameowlia thanks for providing your view on this, we have discussed this case at today's ToC meeting and there was consensus about making an exception for docs areas in this case.

**Pull request merged**
