### PR TITLE
Add Duane May to Identity and Creds reviewers

### PR DESCRIPTION
**Pull request by duanemay**
I would like to start actively contributing to the Identity and Creds repos with the intent to work towards approver status.

### CODE REVIEW

**Comment by beyhan** [comment]
Technically we require two thumps up or approvals from the approvers and then we are good to go.

**Comment by peterhaochen47** [comment]
Duane has joined our team and will play an active role in maintaining our repos and feature development.

**Comment by Tallicia** [comment]
Who's got two thumbs for this? This girl. 👍🏽 👍🏽

**Review by jpalermo — APPROVED** [review]
Two existing approvers have given the 👍

**Pull request merged**
