### PR TITLE
Propose initial set of working groups

### PR DESCRIPTION
**Pull request by emalm**
The description for each proposed working group includes a brief statement of its mission and the projects it will subsume from the PMC governance structure.

Proposing this structure in advance of discussion at the 2021-07-13 TOC meeting, so this proposal should in no way be taken as final. Feedback and counterproposals welcome!

### CODE REVIEW

**Comment by emalm** [comment]
Added a [frame to the Miro board](https://miro.com/app/board/o9J_lJ8wLOE=/?moveToWidget=3074457361298112864&cot=14) from #33 to illustrate this proposal (board password: `workingonit`).
cff-wg-proposal--pr-140--2021-07-12

**Comment by emalm** [comment]
Related PRs for each working group charter:

- App Runtime Deployments: #139 
- App Runtime Interfaces: #141 
- App Runtime Platform: #142 
- Buildpacks: #143 
- Community Experience: #144 
- Foundational Infrastructure: #145 
- Service Management: #146 
- Vulnerability Management: #147

**Comment by davewalter** [comment]
Did y'all consider putting BOSH Bootloader be in the `Foundational Infrastructure` working group, instead of to `App Runtime Deployments`? That might be a better fit, alongside BOSH itself? I know that BBL does have some CF knowledge (the ability to provision load balancers), but it also has similar knowledge for Concourse.

**Comment by emalm** [comment]
Closing this PR in favor of https://github.com/cloudfoundry/community/pull/158.

**Pull request closed without merging**
