### PR TITLE
[ARI] Add Greg Weresch as CLI reviewer

### PR DESCRIPTION
**Pull request by a-b**
@weresch is a seasoned developer who actively participates in CLI development and maintenance. I endorse him as a CLI reviewer.

### CODE REVIEW

**Comment by Gerg** [comment]
Per https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver, you need 2 existing CLI approvers to review the application to affirm that Greg meets the criteria for promotion. Once the review is complete, Stephan or I can merge this PR.

**Comment by Gerg** [comment]
@cloudfoundry/wg-app-runtime-interfaces-cli-approvers for approval

**Comment by gururajsh** [comment]
LGTM

**Review by joaopapereira — APPROVED** [review]
LGTM

**Review by Gerg — APPROVED** [review]
Welcome to ARI!

**Pull request merged**
