### PR TITLE
[RFC0030] Updates

### PR DESCRIPTION
**Pull request by beyhan**
* Service Binding name collision behaviour
 * `VCAP_SERVICES` attribute translation
 * Change `ServiceBindingFiles` to `VolumeMountedFiles` to avoid CF terminology leaking into BBS's domain model
 * `Files` to `File`, `Name` to `Path` and `Value` to `Content` for better readability

### CODE REVIEW

**Comment by beyhan** [comment]
@philippthun,  @dimitardimitrov13 could you pls also check on this updates.

**Comment by PlamenDoychev** [comment]
@dimitardimitrov13, is currently off. Expect update from hiм Monday at the earliest. I'll also take a look.

**Comment by dimitardimitrov13** [comment]
Hello, @beyhan, I'm starting the refactoring for all impacted projects: bbs, protobuffers, rep, executor and diego-release.

**Comment by stephanme** [comment]
@philippthun described the mapping process in details: https://github.com/cloudfoundry/cloud_controller_ng/issues/4036

**Review by stephanme — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Review by ameowlia — APPROVED** [review]

**Review by ChrisMcGowan — APPROVED** [review]

**Comment by dimitardimitrov13** [comment]
Hello,

All changes requested in this PR have been addressed.
Additionally, if there is anything else to adjust or change, please let us know.

Thank you.
Dimitar

**Comment by beyhan** [comment]
Thank you @dimitardimitrov13 for the update! Are there new PRs which we could add to https://github.com/cloudfoundry/community/issues/901?

**Comment by dimitardimitrov13** [comment]
Hello, there are no new PRs. I have addressed the comments above and also fixed the issue that @philippthun discovered with Mkdir. New test cases have been added to cover the implementation in more detail.

**Comment by philippthun** [comment]
I've also adapted my Cloud Controller changes and was able to run an integration test on a bbl environment with modified capi and diego releases. I am now looking into other scenarios (apps, tasks, sidecars, buildpacks, docker, cnb, staging, ...)...

**Pull request merged**
