### PR TITLE
Add myself, mingxiao, as a contributor and reviewer for Bosh

### PR DESCRIPTION
**Pull request by mingxiao**

### CODE REVIEW

**Comment by beyhan** [comment]
Hi @mingxiao,

Thanks for the pr! Could you please add a short description why you are interested to get reviewer. Thanks!

**Comment by mingxiao** [comment]
hey @beyhan , I am a new member of the BOSH Ecosystem team in Broadcom, I see that the other recent members have been added as reviewers.

**Review by rkoster — APPROVED** [review]

**Review by jpalermo — APPROVED** [review]
👍
Ming is currently on our team pairing with us

**Review by beyhan — APPROVED** [review]

**Comment by beyhan** [comment]
Welcome @mingxiao!

**Pull request merged**
