### PR TITLE
Promote Michael Oleske to CLI approver

### PR DESCRIPTION
**Pull request by a-b**
For many years, Michael made valuable contributions to the CLI. I trust Michaels's judgment and am confident he has sufficient expertise to decide what suits this project.

### CODE REVIEW

**Comment by beyhan** [comment]
According to the [promotion rules](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver) one approval is enough in this case because the [CLI areas](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/app-runtime-interfaces.md) has less than 4 approvers. @reedr3 or @jdgonzaleza could one of you attest by a comment this promotion.

**Comment by beyhan** [comment]
For the records the contributions done by @moleske to the CLI are (generated by using the [contributions-for-user.sh script](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/contributions-for-user.sh)):
# App Runtime Interfaces: CLI Contributions
### PRs Commented on/Reviewed:
- 2023-10-12T23:50:54Z: [Add --wait, -w flag to run-task ](https://github.com/cloudfoundry/cli/pull/2611)
- 2023-10-20T17:51:49Z: [Promote changes from develop to the master branch](https://github.com/cloudfoundry/CLAW/pull/67)
### Issues that may be relevant:
- 2022-06-16T22:24:07Z: [Update Contributing to use go 1.18](https://github.com/cloudfoundry/cli/pull/2287)
- 2022-09-15T23:17:55Z: [Use jq instead of grep -P for finding users to delete during integrat…](https://github.com/cloudfoundry/cli/pull/2319)
- 2022-09-16T19:27:42Z: [Allow user to rename app if buildpack is deleted](https://github.com/cloudfoundry/cli/pull/2321)
- 2022-09-22T16:30:19Z: [Use Eventually/Should for routes_command list routes with http1 and](https://github.com/cloudfoundry/cli/pull/2324)
- 2022-10-13T20:34:12Z: [Replace ioutil.ReadFile with embed for fixtures](https://github.com/cloudfoundry/cli/pull/2330)
- 2022-10-13T21:06:29Z: [Explicity enable route_sharing feature on tests that need it](https://github.com/cloudfoundry/cli/pull/2331)
- 2022-10-13T22:39:54Z: [Use default of 1GB memory instead of 32M](https://github.com/cloudfoundry/cli/pull/2332)
- 2022-10-19T23:24:52Z: [Add Isolation Segment](https://github.com/cloudfoundry/cli/pull/2335)
- 2022-10-20T22:41:28Z: [Add OIDC to GitHub Integration Actions](https://github.com/cloudfoundry/cli/pull/2336)
- 2023-02-03T18:19:41Z: [Allow Stack Auditor plugin to work with cf cli 7 and 8](https://github.com/cloudfoundry/stack-auditor/pull/23)
- 2023-02-25T00:32:41Z: [Get to ginkgo v2](https://github.com/cloudfoundry/cli/pull/2378)
- 2023-03-17T18:05:20Z: [Add github actions to test prs](https://github.com/cloudfoundry/stack-auditor/pull/25)
- 2023-03-17T18:29:06Z: [Add dependabot to keep up to date](https://github.com/cloudfoundry/stack-auditor/pull/26)
- 2023-05-05T13:39:19Z: [If changing the stack fails app state is not restored](https://github.com/cloudfoundry/stack-auditor/issues/33)
- 2023-05-05T22:19:39Z: [Remove ubuntu 18.04 and macos-10.15 from unit tests](https://github.com/cloudfoundry/cli/pull/2416)
- 2023-05-05T23:28:31Z: [Use specific ruby buildpack for does_not_stage_on_fs4 app](https://github.com/cloudfoundry/stack-auditor/pull/34)
- 2023-06-14T22:52:28Z: [Bump code.cloudfoundry.org/lager from 1.1.1-0.20191008172124-a9afc05ee5be to 2.0.0+incompatible](https://github.com/cloudfoundry/cli/pull/2463)
- 2023-08-18T22:24:20Z: [Bump depedencies and fix race condition in v7](https://github.com/cloudfoundry/cli/pull/2505)
- 2023-08-18T23:16:22Z: [turn on dependabot for branches v7 and v8 in support](https://github.com/cloudfoundry/cli/pull/2506)
- 2023-08-24T21:10:53Z: [Bump github.com/docker/distribution to 2.8.2](https://github.com/cloudfoundry/cli/pull/2512)
- 2023-08-24T21:17:48Z: [bump github.com/docker/distribution to 2.8.2](https://github.com/cloudfoundry/cli/pull/2513)
- 2023-08-25T17:05:07Z: [keep github actions up to date](https://github.com/cloudfoundry/cli/pull/2517)
- 2023-08-25T17:57:53Z: [Add use latest ruby-buildpack for when we test with older cf-deployments](https://github.com/cloudfoundry/cli-ci/pull/10)
- 2023-08-25T18:11:24Z: [Use latest ruby buildpack v7](https://github.com/cloudfoundry/cli/pull/2518)
- 2023-08-25T18:14:20Z: [Use latest ruby buildpack for min capi tests v8](https://github.com/cloudfoundry/cli/pull/2519)
- 2023-08-25T18:15:31Z: [Use latest ruby buildpack for min capi tests main](https://github.com/cloudfoundry/cli/pull/2520)
- 2023-08-26T02:22:06Z: [Bump actions/download-artifact from 2 to 3](https://github.com/cloudfoundry/cli/pull/2530)
- 2023-08-29T23:35:08Z: [add 8.7.2 release](https://github.com/cloudfoundry/CLAW/pull/56)
- 2023-08-30T22:43:44Z: [add 7.7.2 release](https://github.com/cloudfoundry/CLAW/pull/57)
- 2023-08-30T22:45:14Z: [add 7.7.2 release](https://github.com/cloudfoundry/CLAW/pull/58)
- 2023-08-31T19:52:21Z: [Update release pipeline to fix old concourse resources not supporting aws role arn](https://github.com/cloudfoundry/bosh-package-cf-cli-release/pull/15)
- 2023-09-01T22:26:10Z: [Remove unneeded replace gopkg.in/fsnotify.v1](https://github.com/cloudfoundry/cli/pull/2547)
- 2023-09-01T22:26:27Z: [Remove unneeded replace gopkg.in/fsnotify.v1](https://github.com/cloudfoundry/cli/pull/2548)
- 2023-09-01T22:26:44Z: [Remove unneeded replace gopkg.in/fsnotify.v1](https://github.com/cloudfoundry/cli/pull/2549)
- 2023-09-10T13:56:38Z: [GPG key expired / regression on Linux repository (EXPKEYSIG)](https://github.com/cloudfoundry/cli/issues/2571)
- 2023-09-15T23:53:23Z: [Bump to ginkgo v2](https://github.com/cloudfoundry/ykk/pull/1)
- 2023-09-15T23:58:04Z: [add github action test](https://github.com/cloudfoundry/ykk/pull/2)
- 2023-09-19T21:26:45Z: [Pauseoutputinterception](https://github.com/cloudfoundry/cli/pull/2585)
- 2023-09-22T21:43:10Z: [Make go 1.21 the new minimum](https://github.com/cloudfoundry/cli/pull/2586)
- 2023-09-22T21:49:28Z: [Make go 1.21 the new minimum](https://github.com/cloudfoundry/cli/pull/2587)
- 2023-09-22T21:54:45Z: [Make go 1.21 the new minimum](https://github.com/cloudfoundry/cli/pull/2588)
- 2023-09-22T22:13:43Z: [Remove circular dependency on hydra integration](https://github.com/cloudfoundry/cli/pull/2589)
- 2023-10-18T17:49:26Z: [test v8 branch with dummy change to readme](https://github.com/cloudfoundry/cli/pull/2618)
- 2023-10-18T19:00:18Z: [Remove Eventually statement for enable ssh tip](https://github.com/cloudfoundry/cli/pull/2619)
- 2023-10-19T18:01:47Z: [Update generate release notes to include arm mac packages](https://github.com/cloudfoundry/cli/pull/2629)
- 2023-10-19T18:14:37Z: [Update generate release notes to include arm mac packages](https://github.com/cloudfoundry/cli/pull/2630)
- 2023-10-19T18:20:02Z: [Update generate release notes to include arm mac packages](https://github.com/cloudfoundry/cli/pull/2631)
- 2023-10-23T11:53:58Z: [Add state to buildpacks output](https://github.com/cloudfoundry/cli/pull/2636)
- 2023-10-25T21:31:11Z: [Bump google.golang.org/grpc from 1.58.2 to 1.58.3](https://github.com/cloudfoundry/cli/pull/2639)
- 2023-10-31T17:54:24Z: [Update path for add-persistent-isolation-segment-diego-cell.yml](https://github.com/cloudfoundry/cli/pull/2643)
- 2023-10-31T17:55:52Z: [Update path for add-persistent-isolation-segment-diego-cell.yml](https://github.com/cloudfoundry/cli/pull/2644)
- 2023-10-31T17:56:38Z: [Update path for add-persistent-isolation-segment-diego-cell.yml](https://github.com/cloudfoundry/cli/pull/2645)
- 2023-10-31T19:20:13Z: [Put back old test/add-persistent-isolation-segment-diego-cell.yml path](https://github.com/cloudfoundry/cli/pull/2646)
- 2023-10-31T19:20:56Z: [Put back old test/add-persistent-isolation-segment-diego-cell.yml path](https://github.com/cloudfoundry/cli/pull/2647)
- 2023-11-01T18:43:46Z: [Bump go log cache and go loggregator main](https://github.com/cloudfoundry/cli/pull/2648)
- 2023-11-01T18:44:37Z: [Bump go log cache and go loggregator v8](https://github.com/cloudfoundry/cli/pull/2649)
- 2023-11-01T18:45:20Z: [Bump go log cache and go loggregator v7](https://github.com/cloudfoundry/cli/pull/2650)
### Code contributions:
- 2021-08-26T16:38:40Z: [Update repo-index.yml](https://github.com/cloudfoundry/cli-plugin-repo/commit/7350349c4fb550831f7b1d36ad169c435c6262ee)
- 2021-08-26T16:39:23Z: [update metric registrar](https://github.com/cloudfoundry/cli-plugin-repo/commit/d2e1a4fed52b09bc6e3a3a8d3c0fd6e923329fc1)
- 2022-06-16T22:22:23Z: [Update Contributing to use go 1.18](https://github.com/cloudfoundry/cli/commit/82f39a3eaa8434e9d6be57d908fee4f4a3014087)
- 2022-09-20T21:13:42Z: [Use jq instead of grep -P for finding users to delete during integrat… (#2319)](https://github.com/cloudfoundry/cli/commit/c67c88ecb65a589307f5899683ea2f28ae746824)
- 2022-09-20T21:25:07Z: [Allow user to rename app if buildpack is deleted (#2321)](https://github.com/cloudfoundry/cli/commit/eb52f6e594731164aec91024a08ffebb3a8fd87b)
- 2022-09-22T18:35:11Z: [Use Eventually/Should for routes_command list routes with http1 and (#2324)](https://github.com/cloudfoundry/cli/commit/a4ae5d18d028d125433c446427075c127e3e9034)
- 2022-10-13T20:29:23Z: [Replace ioutil.ReadFile with embed for fixtures](https://github.com/cloudfoundry/cli/commit/c5839d5b757b15104c6d6f8c4f84af554feadf01)
- 2022-10-13T22:36:46Z: [Use default of 1GB memory instead of 32M](https://github.com/cloudfoundry/cli/commit/711a3469face4fcc81ab3e9d4d3af6d293de4a1d)
- 2022-10-20T22:28:54Z: [Deploys OIDC provider for github integration tests](https://github.com/cloudfoundry/cli/commit/27ae058fcdb24db4730a4b1a962fac4631038a04)
- 2022-10-21T21:39:47Z: [Add Isolation Segment to GitHub Actions Integration Tests (#2335)](https://github.com/cloudfoundry/cli/commit/4b0fcc0b443efedd7a1b99615fc46fe60e3077eb)
- 2022-10-21T21:59:22Z: [Explicity enable route_sharing feature on tests that need it (#2331)](https://github.com/cloudfoundry/cli/commit/426fde62cceb2afcc031be805b2d00d692632626)
- 2023-01-26T22:52:32Z: [Add cflinuxfs4 - wip](https://github.com/cloudfoundry/stack-auditor/commit/59ec411e53888e29c2ea4236e77b08c9830cb489)
- 2023-01-27T00:51:36Z: [Add an app that errors on cflinuxfs4](https://github.com/cloudfoundry/stack-auditor/commit/9144659c898e7933c305ddbbe74209cc5aaa8bc8)
- 2023-01-31T00:54:12Z: [shell out to cf restart - wip](https://github.com/cloudfoundry/stack-auditor/commit/49e6d64057f820499bd1ce9dc435c0badb332206)
- 2023-02-01T23:46:49Z: [Fix zero downtime when app fails to run](https://github.com/cloudfoundry/stack-auditor/commit/acf2facc7f76cb9f2ecb859f0da4a5b3ef2a277d)
- 2023-02-02T00:48:33Z: [Convert integration tests to ginkgo from spec](https://github.com/cloudfoundry/stack-auditor/commit/6681c82fb275dabf85e8e574a5c7c2c26cfa3382)
- 2023-02-02T21:13:52Z: [Use cf restage instead of restart](https://github.com/cloudfoundry/stack-auditor/commit/b71ec4ac52da1dd48d1326eb9a4e86758397cfa3)
- 2023-02-02T23:51:07Z: [Remove unused features](https://github.com/cloudfoundry/stack-auditor/commit/195f976b4021225b151f12b7fd642eda8fa12176)
- 2023-02-03T00:10:55Z: [Remove unused testdata and update run the tests section of the readme](https://github.com/cloudfoundry/stack-auditor/commit/46a82e3c99e87a44e57c051cd7c5db963238f94c)
- 2023-02-03T00:53:48Z: [Replace spec with ginkgo](https://github.com/cloudfoundry/stack-auditor/commit/2fefbcb4374b6a6010a0702fc95e3129b4086c0c)
- 2023-02-14T19:49:56Z: [Fix integration and unit test scripts](https://github.com/cloudfoundry/stack-auditor/commit/0ef04dbab7048ddb8cedb4bb480d8867d7706976)
- 2023-02-14T19:52:53Z: [Remove deprecated pkg/errors in favor of go's standard errors library](https://github.com/cloudfoundry/stack-auditor/commit/a6dd8684c53e9e8bb8e28a86680238a9b0ca1e07)
- 2023-02-14T22:07:30Z: [bump libbuildpack to latest](https://github.com/cloudfoundry/stack-auditor/commit/ff5a6693d3ae8498fb45885cd101035bdb0b6451)
- 2023-02-14T22:31:53Z: [bump cli to 7.1.0](https://github.com/cloudfoundry/stack-auditor/commit/87a12c8511110eef0d05e3a9332f821b302410de)
- 2023-03-17T22:19:47Z: [Add github actions to test prs (#25)](https://github.com/cloudfoundry/stack-auditor/commit/4394958a136fe9dbcfb96b9123c504f8e1866a01)
- 2023-03-17T22:21:32Z: [Add dependabot to keep up to date (#26)](https://github.com/cloudfoundry/stack-auditor/commit/37fe2f5bba7364d483b6a78325cac700ac9b7043)
- 2023-05-05T23:27:45Z: [Use specific ruby buildpack for does_not_stage_on_fs4 app](https://github.com/cloudfoundry/stack-auditor/commit/0076eba43255f5c111a631e4cb43b868cf89ebd8)
- 2023-05-20T01:07:33Z: [remove unzip instructions in readme](https://github.com/cloudfoundry/stack-auditor/commit/b0b8d692e05d0377f61866af3511f51b0788741a)
- 2023-08-18T23:07:26Z: [turn on dependabot for branches v7 and v8 in support](https://github.com/cloudfoundry/cli/commit/8bbd72c8605f107b7054b8341662568134487bf7)
- 2023-08-25T17:04:23Z: [keep github actions up to date](https://github.com/cloudfoundry/cli/commit/84ab330381464108dfb81b9ca61f93ea67219d07)
- 2023-08-25T17:55:13Z: [Add use latest ruby-buildpack for when we test with older cf-deployments](https://github.com/cloudfoundry/cli-ci/commit/598d717b69be970140834d673c550a6a01d6d14b)
- 2023-08-25T18:05:43Z: [Use latest ruby buildpack for min capi tests](https://github.com/cloudfoundry/cli/commit/323ed930178d5036423947f051fce55f7975d736)
- 2023-08-29T23:52:16Z: [release 8.7.2](https://github.com/cloudfoundry/CLAW/commit/3edadf316d6948440ae54c3a8bd1c7618c8cb565)
- 2023-08-30T23:22:56Z: [add 7.7.2 release (#58)](https://github.com/cloudfoundry/CLAW/commit/ada51c3b1b10ca0e95244fedd4773c2e765bf919)
- 2023-10-12T15:24:33Z: [Make go 1.21 the new minimum (#2586)](https://github.com/cloudfoundry/cli/commit/03b292514385b6efb0909940c3a71590f1250929)
- 2023-10-27T22:09:52Z: [Use harbor proxy to fetch cfcli/cli-base image](https://github.com/cloudfoundry/cli-private/commit/80538265483f31895993ee40b6ae2cbe786e5ae7)
- 2023-10-31T18:33:26Z: [Update path for add-persistent-isolation-segment-diego-cell.yml (#2643)](https://github.com/cloudfoundry/cli/commit/04a5471cf5ec15b88e7c0b21769fbaa0e83d34f2)
- 2023-10-31T20:14:30Z: [Put back old test/add-persistent-isolation-segment-diego-cell.yml path (#2646)](https://github.com/cloudfoundry/cli/commit/251bf5f71b78af37f6e91b555a092ff2b439a33e)
- 2023-11-01T22:57:09Z: [Bump go log cache and go loggregator main (#2648)](https://github.com/cloudfoundry/cli/commit/b3028f4a141d156d7730f959d5b63c40556951c1)
- 2023-11-16T16:26:19Z: [Update generate release notes to include arm mac packages (#2629)](https://github.com/cloudfoundry/cli/commit/00ffc99c84c25813eaa4fb8e516148dd518492d7)

**Comment by ccjaimes** [comment]
I support Michael's promotion to a CLI Approver!

**Review by ccjaimes — APPROVED** [review]

**Comment by a-b** [comment]
@beyhan I confirm that this promotion is still relevant. Thank you for taking the time to double-check.

**Review by Gerg — APPROVED** [review]
Congratulations on your promotion!

**Comment by Gerg** [comment]
Merging this PR is currently blocked on resolving merge conflicts.

**Comment by beyhan** [comment]
@a-b could you please resolve the conflicts so that we can merge it.

**Comment by ameowlia** [comment]
✅ resolved merge conflicts and merged. Congrats @moleske!

**Pull request merged**
