### PR TITLE
Add Sascha Stojanovic to VM deployment lifecycle (BOSH)

### PR DESCRIPTION
**Pull request by Sascha-Stoj**
New teammember in BOSH Team at SAP

### CODE REVIEW

**Comment by rkoster** [comment]
Please run the following script to generate a list of contributions: https://github.com/cloudfoundry/community/blob/main/toc/working-groups/contributions-for-user.sh

If the requirements for approver status have not yet been met, please update the PR to reviewer status: https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#reviewer

**Comment by beyhan** [comment]
Hi @Sascha-Stoj,

I ran the proposed script by Ruben and looks like that the requirements for the approver status (https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#requirements-3) are not yet met. Could you please update the pr to reviewer status.

**Review by Sascha222 — APPROVED** [review]
reviewed by myself

**Comment by beyhan** [comment]
closing in favour of https://github.com/cloudfoundry/community/pull/997

**Pull request closed without merging**
