### PR TITLE
Add notifications bot and remove dead approvers

### PR DESCRIPTION
**Pull request by dsboulder**
We're resurrecting and fixing up notifications, yay!

### CODE REVIEW

**Comment by dsboulder** [comment]
@Gerg could you take a look?

**Comment by Gerg** [comment]
Per https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-approver, promotion applications require 2 existing approvers to review and validate that @reedr3 meets the [approver criteria](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#requirements-3).

**Comment by dsboulder** [comment]
The cryo folks (Diego, Rather, Fernando) were likely going to become the owners of this component, but they said no after we had made the original YAML. 🤷

**Review by Gerg — APPROVED** [review]
Given the special circumstance, I'm approving this PR. Once this project is healthy again, we will resume normal order.

**Pull request merged**
