### PR TITLE
Add Daniel Garnier-Moiroux as UAA contributor

### PR DESCRIPTION
**Pull request by Kehrlann**
Hey team 👋

I'm Daniel, from the Spring team at Broadcom. I'm going to start contributing to the UAA.

As discussed in the maintainers call, here's my PR.

cc @duanemay @strehle @coolgang123

### CODE REVIEW

**Review by strehle — APPROVED** [review]
@beyhan OK

**Review by duanemay — APPROVED** [review]
Welcome to UAA @Kehrlann !

**Comment by strehle** [comment]
@Kehrlann after CLA is green you can also start with PRs to uaa directly...

**Review by coolgang123 — APPROVED** [review]
Welcome Daniel !

**Review by beyhan — APPROVED** [review]

**Comment by beyhan** [comment]
Welcome @Kehrlann! 

Also, to merge this pr we will need the CLA signed.

**Comment by Kehrlann** [comment]
Thanks @beyhan ! On it, currently chasing the correct approvers within the company to get the CLA sorted.

**Comment by Kehrlann** [comment]
@beyhan done!

**Comment by strehle** [comment]
@Kehrlann with the CLA you can start creating PRs to https://github.com/cloudfoundry/uaa so you do not have to wait until you are fully onboarded

**Comment by strehle** [comment]
@jpalermo Hi, the PR was merge a while ago, but I cannot see @Kehrlann neither in the Org nor in teams (with pattern uaa), so can you please check what went wrong, thanks in advance.

**Comment by strehle** [comment]
> @Kehrlann pls accept the invitations you got.

@beyhan Thank you

**Pull request merged**
