### PR TITLE
Adding Greg Meyer as reviewer for bosh

### PR DESCRIPTION
**Pull request by gm2552**

### CODE REVIEW

**Comment by gm2552** [comment]
A request has been made to for approval by the CLA manager.

**Comment by beyhan** [comment]
Hi @gm2552,

thank you for this pr! Could you please add some context why you would like to contribute, sign the CLA (in case you face an issue here please comment) and please add yourself to the https://github.com/cloudfoundry/community/blob/main/org/contributors.yml.

**Comment by gm2552** [comment]
> Hi @gm2552,
> 
> thank you for this pr! Could you please add some context why you would like to contribute, sign the CLA (in case you face an issue here please comment) and please add yourself to the https://github.com/cloudfoundry/community/blob/main/org/contributors.yml.

Context: I've been added to the BOSH Ecosystem and VMware/Broadcom.

Added Git handel as a contributor to requested file.  Request has been sent to the CLA manager to authorize.

**Review by rkoster — APPROVED** [review]

**Review by beyhan — APPROVED** [review]

**Comment by beyhan** [comment]
@gm2552 could you please resolve the merge conflicts so that we can merge this.

**Comment by gm2552** [comment]
Resolved

**Review by jpalermo — APPROVED** [review]

**Pull request merged**
