### PR TITLE
Remove  metric store team members who've left VMware

### PR DESCRIPTION
**Pull request by jbooherl**
Removing members who did not receive offers with the Broadcom transition

### CODE REVIEW

**Comment by beyhan** [comment]
According to our [Revoking Reviewer or Approver Role](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#revoking-reviewer-or-approver-role) @hmanukyanVMw, @gggevorgyan and @myeghiazarya have two weeks to refute the revocation starting from the creation of this pr.

**Comment by beyhan** [comment]
@jbooherl I don't know why the EasyCLA check is failing on this pr. Could it be that you used a different email for the commit or you could try to repush to re-trigger the check.

**Comment by beyhan** [comment]
@jbooherl will be great if you could resolve the merge conflicts. After that this should be ready for merge @ameowlia, @emalm

**Comment by jbooherl** [comment]
Thank for your patience. I merged in the latest changes

**Comment by beyhan** [comment]
All fine. @ameowlia or @emalm this can be merged.

**Review by emalm — APPROVED** [review]

**Pull request merged**
