### PR TITLE
Move the ali repositories into a sub area

### PR DESCRIPTION
**Pull request by mvach**

### CODE REVIEW

**Comment by beyhan** [comment]
@xiaozhu36 could you please review this and put a dumps up if it is fine for you.

**Review by xiaozhu36 — CHANGES_REQUESTED** [review]
Please don't add the approver for the repo cloudfoundry/bosh-ali-storage-cli

**Comment by xiaozhu36** [comment]
HI @beyhan Can I have maintainer permission so that I can merge PR and publish new releases?

**Comment by xiaozhu36** [comment]
@beyhan Sounds better. I am ok.

**Review by beyhan — APPROVED** [review]

**Review by jpalermo — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Pull request merged**
