### PR TITLE
UAA go CLI

### PR DESCRIPTION
**Pull request by strehle**
cloudfoundry-incubator/uaa-cli
Question should we move it into cloudfoundry ? or archive
There is a pipeline setup which could be used
https://hush-house.pivotal.io/teams/cf-uaa/pipelines/uaa-cli

### CODE REVIEW

**Comment by beyhan** [comment]
I added this topic to the [Foundational Infrastructure WG agenda](https://docs.google.com/document/d/1pLKTANki82JsCqPr4DE8vu4je_omA20eH96CUuRW_8Q) for the next WG meeting. Unfortunately, this Thursday is a holiday in Germany but most probably we could discuss this next week.

**Comment by strehle** [comment]
@beyhan unfortunatly I cannot join today, but for this topic I simply dont if CF community want a uaa go client or if uaac is enough. if uaa-cli (go) should stay alive then please add UAA maintainers to this repo if not, then I ask you to archive the repo

**Review by rkoster — APPROVED** [review]
LTGM

**Review by beyhan — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Comment by strehle** [comment]
@rkoster is there a reason why this PR is not merged yet ? I ask because I cannot work on uaa-cli and update repo if I have no access. I understood so far, that with this PR you manage priviledges to repos

**Comment by rkoster** [comment]
@LeePorte Can I go ahead and merge this PR, or should this one be discussed at next ToC meeting?

**Comment by LeePorte** [comment]
@rkoster this is a working group level PR, if the working group is happy for you to merge, go for it!

**Comment by strehle** [comment]
@rkoster can you please check why I cannot merge to https://github.com/cloudfoundry/uaa-cli . I wanted work in some dependency updates

**Pull request merged**
