### PR TITLE
move benjamintf1 to approver for capi

### PR DESCRIPTION
**Pull request by Benjamintf1**
Hi. Long time contributor to cf. 

I've collected a few Capi Contributions:

1. https://github.com/cloudfoundry/cloud_controller_ng/pull/3270
1. https://github.com/cloudfoundry/cloud_controller_ng/pull/3098
1. https://github.com/cloudfoundry/cloud_controller_ng/pull/2900
1. https://github.com/cloudfoundry/capi-release/pull/266
1. https://github.com/cloudfoundry/capi-release/pull/73#issuecomment-413235080
1. https://github.com/cloudfoundry/capi-release/pull/163#issuecomment-606735820
1. https://github.com/cloudfoundry/capi-release/pull/94
1. worked with Michael Oleske on updating the capi certs for capi. 
1. https://cloudfoundry.slack.com/archives/C07C04W4Q/p1680196229614289
1. https://cloudfoundry.slack.com/archives/C07C04W4Q/p1540491354000100
1. https://cloudfoundry.slack.com/archives/C07C04W4Q/p1522165747000724
1. https://github.com/cloudfoundry/capi-ci/pull/41
1. https://github.com/cloudfoundry/cloud_controller_ng/pull/3450
1. https://github.com/cloudfoundry/cloud_controller_ng/pull/3461
1. https://github.com/cloudfoundry/cloud_controller_ng/pull/3503
1. https://github.com/cloudfoundry/cloud_controller_ng/pull/3659

And I'm looking to be more involved in capi work in the future.

### CODE REVIEW

**Comment by stephanme** [comment]
Hi @Benjamintf1,
according to [rfc-0008-role-change-process](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0008-role-change-process.md) you would need 4 more contributions (PRs, issues and discussions e.g. #capi channel will do as well).
In addition, two existing capi approvers need to give their +1.
Since you are a long term contributor to CF and you have worked in the logging area before, I could imagine to grant you approver rights on a fast-track (i.e. without waiting for 4 additional contributions) if existing capi approvers support this.
Best regards, Stephan

**Comment by sethboyles** [comment]
As a CAPI approver, I support fast-tracking @Benjamintf1 as an approver.

**Comment by moleske** [comment]
just cause I don't see it here will point out at least one issue Ben has filed against cloud_controller_ng https://github.com/cloudfoundry/cloud_controller_ng/issues/3506 to tack on the list of contributions

giving my approval as well as a CAPI approver

**Comment by beyhan** [comment]
@Benjamintf1 this is still a DRAFT. Is this by intention?

**Review by philippthun — APPROVED** [review]

**Comment by philippthun** [comment]
+1

**Comment by stephanme** [comment]
@Benjamintf1: Needed approvals are there now. If you make the PR 'ready for review' (= remove draft), I would merge it.

**Pull request merged**
