### PR TITLE
[ARI] Promote Greg Weresch to CLI approvers

### PR DESCRIPTION
**Pull request by a-b**
Greg demonstrated advanced knowledge in CF CLI, Golang, and software engineering. I propose promoting him to approver.

### CODE REVIEW

**Comment by Gerg** [comment]
Per https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver, you need 2 existing CLI approvers to review the application to affirm that Greg meets the criteria for promotion. Once the review is complete, Stephan or I can merge this PR.

cc @cloudfoundry/wg-app-runtime-interfaces-cli-approvers

**Comment by gururajsh** [comment]
LGTM

**Comment by Samze** [comment]
LGTM

**Comment by joaopapereira** [comment]
LGTM

**Comment by a-b** [comment]
LGTM - but I can't approve my PR. @Gerg can you please approve this?

**Review by Gerg — APPROVED** [review]

**Pull request merged**
