### PR TITLE
Move repos from bosh-prometheus GH org to cloudfoundry GH org

### PR DESCRIPTION
**Pull request by gberche-orange**
See related https://github.com/cloudfoundry/community/issues/787#issuecomment-2014593227

### CODE REVIEW

**Review by rkoster — APPROVED** [review]

**Review by stephanme — APPROVED** [review]

**Comment by beyhan** [comment]
@ArthurHlt @benjaminguttmann-avtq @bkez322 @frodenas @gmllt @mdimiceli @mkuratczyk could you please put a dumps up as approval.

**Review by ameowlia — APPROVED** [review]

**Review by ChrisMcGowan — APPROVED** [review]

**Comment by beyhan** [comment]
FYI @ArthurHlt @benjaminguttmann-avtq @bkez322 @frodenas @gmllt @mdimiceli @mkuratczyk we plan to merge this next Tuesday 23th of April. Pls comment if you don't want it.

**Review by beyhan — APPROVED** [review]

**Comment by beyhan** [comment]
@gberche-orange The merge of this pr will trigger the our automation to generate the repositories but actual move needs to be done by @christopherclark. Is it possible to make Chris admin of the bosh-prometheus org for that?

**Comment by christopherclark** [comment]
Hello @gberche-orange and @stephanme. Pardon the delay - I was out at a conference last week. I just transferred the five repositories listed in the commit! Hopefully, the automation will update permissions shortly. Please let me know if anything looks amiss.

**Pull request merged**
