### PR TITLE
Networking components reviewer update

### PR DESCRIPTION
**Pull request by Dariquest**
Daria Anton: 

A couple of contributions and reviews were done already, e.g. :

https://github.com/cloudfoundry/gorouter/pull/428
https://github.com/cloudfoundry/haproxy-boshrelease/pull/711

### CODE REVIEW

**Comment by Dariquest** [comment]
@ameowlia Hi Amelia :)

**Comment by Mrizwanshaik** [comment]
Mrizwanshaik:

Contributions:
https://github.com/cloudfoundry/gorouter/pull/324
https://github.com/cloudfoundry/haproxy-boshrelease/pull/659
https://github.com/cloudfoundry/haproxy-boshrelease/pull/397
https://github.com/cloudfoundry/haproxy-boshrelease/pull/419
https://github.com/cloudfoundry/haproxy-boshrelease/pull/440

**Comment by hoffmaen** [comment]
My only contribution so far:
* https://github.com/cloudfoundry/gorouter/pull/435

**Review by ameowlia — APPROVED** [review]

**Comment by ameowlia** [comment]
🎉 Welcome!

**Comment by Dariquest** [comment]
Thanks, Amelia! @ameowlia

**Pull request merged**
