### PR TITLE
Add Bruce Ricard to CredHub and UAA approvers

### PR DESCRIPTION
**Pull request by bruce-ricard**

### CODE REVIEW

**Comment by bruce-ricard** [comment]
cc: @rizwanreza

**Comment by bruce-ricard** [comment]
Some check is failing:

>{
  "component": "peribolos",
  "file": "k8s.io/test-infra/prow/cmd/peribolos/main.go:188",
  "func": "main.main",
  "level": "fatal",
  "msg": "Configuration failed: failed to list cloudfoundry invitations: return code not 2XX: 401 Unauthorized",
  "severity": "fatal",
  "time": "2022-07-07T14:40:48Z"
}

Do I need to do something about that?

**Comment by stephanme** [comment]
Strange, the same operation (list cloudfoundry invitations) succeeds in workflow [Sync Github Organization Settings](https://github.com/cloudfoundry/community/actions/workflows/org-management.yml) and other PRs validate as well like #336.

I retriggered the validation but it failed again. No real idea at the moment.
@rkoster: Did you see such errors before? 

I suggest to go on with the role change process (you need one more +1 by a WG area approver) and then merge even if the check still fails.

**Comment by emalm** [comment]
@peterhaochen47 Could you please approve adding @bruce-ricard as an approver in the CredHub and UAA areas? You're the only approver in both areas. Thanks!

**Comment by bruce-ricard** [comment]
Thank you folks!

**Pull request merged**
