### PR TITLE
Add UAA pipeline project

### PR DESCRIPTION
**Pull request by strehle**
https://github.com/cloudfoundry/identity-ci contains configuration of concourse, running 
https://hush-house.pivotal.io/teams/cf-uaa/pipelines/uaa-acceptance-gcp

### CODE REVIEW

**Comment by beyhan** [comment]
I added this topic to the [Foundational Infrastructure WG agenda](https://docs.google.com/document/d/1pLKTANki82JsCqPr4DE8vu4je_omA20eH96CUuRW_8Q) for the next WG meeting. Unfortunately, this Thursday is a holiday in Germany but most probably we could discuss this next week.

**Comment by strehle** [comment]
@beyhan unfortunatly I cannot join today, 
Here I created Github Action for local build already, e.g. https://github.com/cloudfoundry/cf-uaa-lib/actions/runs/1691547027 and  for release or deploy to https://rubygems.org/gems/cf-uaa-lib I simply need one owner of https://rubygems.org/profiles/cf in order to create a secret in https://github.com/cloudfoundry/cf-uaa-lib so that we can use simply the github action to deploy to rubygems

@rkoster are you able to get API token from https://rubygems.org/profiles/cf ?
If the github actions works, then I or we (externals) dont need access to https://github.com/cloudfoundry/identity-ci

**Review by rkoster — CHANGES_REQUESTED** [review]
@strehle could you take a look at the changes as requested here: https://github.com/cloudfoundry/community/pull/184#issuecomment-1010078023

**Comment by strehle** [comment]
ok, changed section according to https://github.com/cloudfoundry/community/pull/184#issuecomment-1010078023

**Review by rkoster — APPROVED** [review]
LGTM

**Review by beyhan — APPROVED** [review]

**Comment by emalm** [comment]
@strehle Could you please update this PR (or create a new one) to add this repo into the embedded YAML structure now present in https://github.com/cloudfoundry/community/blob/main/toc/working-groups/foundational-infrastructure.md?

**Comment by strehle** [comment]
not sure what you mean, because before it was in the structure, but this is a private repo and I was asked to change this. close this PR

**Pull request closed without merging**
