### PR TITLE
Strawman: How would projects map to working groups?

### PR DESCRIPTION
**Pull request by loewenstein**
This is meant as a strawman to get something out. It definitely needs input from the community and projects, if the grouping would make sense for them.

### CODE REVIEW

**Comment by gcapizzi** [comment]
What do people think about having different WGs for CF-on-VMs vs CF-on-K8s?

I'm on the Eirini team, and while we have context con both worlds for historical reasons (we are 100% made of people who worked on Garden and we still maintain Garden to this day), it doesn't look like the Diego/Garden stack could share a Roadmap with Eirini.

**Comment by chipchilders** [comment]
> What do people think about having different WGs for CF-on-VMs vs CF-on-K8s?
> 
> I'm on the Eirini team, and while we have context con both worlds for historical reasons (we are 100% made of people who worked on Garden and we still maintain Garden to this day), it doesn't look like the Diego/Garden stack could share a Roadmap with Eirini.

This comment makes a ton of sense. At this point, this PR is sitting here as a starting point for the TOC to use *once the TOC exists*. All of the current projects will need to be appropriately structured. Keep comments / ideas like this coming! :)

**Comment by emalm** [comment]
Adding a link to the [public Miro board](https://miro.com/app/board/o9J_lJ8wLOE=/) where we played around with mapping the existing projects to new working groups, plus a snapshot of the frame for posterity: [[Public] CFF Working Groups scratch space - 2021-04-16.pdf](https://github.com/cloudfoundry/community/files/6326389/Public.CFF.Working.Groups.scratch.space.-.2021-04-16.pdf).

**Comment by emalm** [comment]
Added the password `workingonit` to the public [Miro board](workingonit) as a screen-door level of security (FYI @loewenstein @bkrannich @norman-abramovitz @jenspinney @chipchilders).

**Comment by loewenstein** [comment]
obsolete

**Pull request closed without merging**
