### PR TITLE
Rename repo as we no longer use gke for the concourse

### PR DESCRIPTION
**Pull request by jpalermo**

### CODE REVIEW

**Review by beyhan — APPROVED** [review]

**Review by rkoster — CHANGES_REQUESTED** [review]
Woudn't `fiwg` or `fi` be more appropriate? Or is this repo still reusable enough to justify using the `cff` suffix?

**Comment by jpalermo** [comment]
Good question. That's something @ramonskie and I were talking about.

It's not currently in that state, and would require some work to make it more generic. Is there a desire for that, or should we make it `fi` specific?

**Comment by beyhan** [comment]
Other WG decided to go with a slightly different approach available in https://github.com/cloudfoundry/app-runtime-interfaces-infrastructure/. I would say that currently there is no desire and we shouldn't do the extra effort. I would vote for `fiwg` in this case.

**Comment by jpalermo** [comment]
PR updated with new name

**Review by beyhan — APPROVED** [review]

**Comment by beyhan** [comment]
ping @rkoster

**Review by rkoster — APPROVED** [review]

**Pull request merged**
