### PR TITLE
Add bobbygeeze as doc approver

### PR DESCRIPTION
**Pull request by bobbygeeze**
I am a new docs writer from VMware and am requesting to become an approver for all docs areas.

This affects 3 working groups and requires approval from the tech leads in each working group:
* App Runtime Platform - @ameowlia
* App Runtime Interfaces - @gerg
* Foundational Infrastructure - @beyhan and/or @rkoster

### CODE REVIEW

**Comment by rkoster** [comment]
@bobbygeeze please resolve the Easy CLA check first

**Comment by bobbygeeze** [comment]
New hire: please tell me how to resolve the CLA check?  Thanks

From: Ruben Koster ***@***.***>
Date: Monday, February 13, 2023 at 7:47 AM
To: cloudfoundry/community ***@***.***>
Cc: Bob Graczyk (c) ***@***.***>, Mention ***@***.***>
Subject: Re: [cloudfoundry/community] Add bobbygeeze as doc approver (PR #533)
!! External Email

@bobbygeeze<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fbobbygeeze&data=05%7C01%7Cbobg%40vmware.com%7C29ab964c5bbe4ba49cf008db0dc06eab%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638118892378738501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EDggVJFxEpro4LzRwL7JPxl1DJpVDjTIbXe2whke74I%3D&reserved=0> please resolve the Easy CLA check first

—
Reply to this email directly, view it on GitHub<https://github.com/cloudfoundry/community/pull/533#issuecomment-1427883288>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5UL3K42UUE236SQXISDPQLWXIUNDANCNFSM6AAAAAAUWYTJAY&data=05%7C01%7Cbobg%40vmware.com%7C29ab964c5bbe4ba49cf008db0dc06eab%7Cb39138ca3cee4b4aa4d6cd83d9dd62f0%7C0%7C0%7C638118892378738501%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=%2FlEpHjqN6Ptxbw1EX9jwfU2rJnUDUbyVY3vL1ThnXrA%3D&reserved=0>.
You are receiving this because you were mentioned.Message ID: ***@***.***>

!! External Email: This email originated from outside of the organization. Do not click links or open attachments unless you recognize the sender.

**Comment by rkoster** [comment]
Please follow the instructions in: https://github.com/cloudfoundry/community/pull/533#issuecomment-1424476984

**Review by ameowlia — APPROVED** [review]

**Comment by ameowlia** [comment]
CLA is now signed.

I approve for the ARP group. Waiting on:
* App Runtime Interfaces - @Gerg
* Foundational Infrastructure - @beyhan and/or @rkoster

**Review by rkoster — APPROVED** [review]

**Pull request merged**
