### PR TITLE
Add Julian to the list of Korifi approvers in the CF on K8s working group

### PR DESCRIPTION
**Pull request by davewalter**

### CODE REVIEW

**Comment by emalm** [comment]
Thanks, @davewalter ! It'd be great to follow the promotion process in https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-approver, even just as a formality. /cc @gcapizzi @georgethebeatle

**Comment by julian-hj** [comment]
> Thanks, @davewalter ! It'd be great to follow the promotion process 

As I read that promotion process, the first step was to create a PR (which is this PR, I think) and then we need 2 approvers unless a TOC member merges it, which they can do without any approvers.

Does that sound right?

**Review by tcdowney — APPROVED** [review]

**Comment by emalm** [comment]
Yep, that's right about needing 2 👍 's from area approvers, and I'd be happy to merge if the WG leads are unavailable. https://github.com/cloudfoundry/community/pull/368 is an exemplary example of the contribution evidence that corresponds to the [approver role criteria](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#requirements-3).

**Review by clintyoshimura — APPROVED** [review]
LGTM

**Review by emalm — APPROVED** [review]

**Comment by emalm** [comment]
Merging as a proxy for @gcapizzi and @georgethebeatle .

**Pull request merged**
