### PR TITLE
Add draft RFC for aggregate metric egress with OTel Collector

### PR DESCRIPTION
**Pull request by ctlong**
For easier viewing: https://github.com/loggregator/community/blob/rfc-otel-collector/toc/rfc/rfc-draft-aggregate-metric-egress-with-opentelemetry-collector.md

cc @mkocher, @acrmp, @rroberts2222

### CODE REVIEW

**Comment by chombium** [comment]
I really like and support the idea of adding OpenTelemetry to Cloud Foundry, but I find the motivation and the problem statement a bit misleading.

Yes, the Firehose architecture has its own disadvantages, because of the aggregation components (Dopplers and RLPs), the effects of misbehaving noisy applications on the flow of log envelopes and some unmaintained plugins and libraries, but it supports collection and forwarding of logs and metrics. As we all work with the `Never touch a running system` motto it is hard to believe that someone would do something if we don't say that we will deprecate and remove the Firehose.

On the other side, the Syslog drains require some more effort to do the implementation right in case  someone wants to use the Syslog protocol and the HTTP based Syslog drains does not support high throughput rates, but they also forward logs and metrics.

By using OpenTelemetry we could solve these problems, but I'm wondering few things:
- Why does this RFC cover only forwarding of metrics? Would this be an initial setup/implementation only for metrics as there are existing out-of-the-box Open Telemetry Collector [receivers](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver) and [exporters](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter) which will be used so we can start experimenting with OpenTelemetry and we will add support for logs and Zipkin traces later? The OpenTelemetry Collector, the way it is defined in this proposal cannot be a replacement neither for the Firehose nor for the Syslog Drains.

- Why is the existence of multiple Open Telemetry Collector exporters (the ability to export the data in different formats) promoted as main selling point which will help the metric consumers? IMO this is a positive side effect of using OpenTelemetry.

OpenTelemetry's main goal is to standardize instrumentation tools for applications and combine logs, metrics and traces in order to provide better observability. I think that it would be better instead of hooking the receiver to the `metrics-agent`, that we build a custom receiver which will be connected directly to the `forwarder agent` and have application and platform component metrics and application logs at hand. We could even do some changes to the [syslog-release](https://github.com/cloudfoundry/syslog-release) to forward the platform component logs to the collector. This way we could build a custom processor, correlate all logs and metrics, enrich them with some spans and extra attributes. That would be essential help for the Cloud Foundry operators as they will have all connected data at hand to quickly see what's going on and immediately take the actions needed.

- There are some planed changes to the `metrics-agent`. We should be careful, not to break anything and stay backward compatible.


Generally speaking, I think that this RFC is a good start to introduce OpenTelemetry to Cloud Foundry, but there will be long way to go until an OpenTelemetry based solution can replace the Firehose or even the Syslog drains.

**Comment by ctlong** [comment]
Hey @chombium, thanks for the detailed response! Let me address it in parts.

> Why does this RFC cover only forwarding of metrics? Would this be an initial setup/implementation only for metrics as there are existing out-of-the-box Open Telemetry Collector [receivers](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/receiver) and [exporters](https://github.com/open-telemetry/opentelemetry-collector-contrib/tree/main/exporter) which will be used so we can start experimenting with OpenTelemetry and we will add support for logs and Zipkin traces later?

I think you're correct in your assessment. In the short-term, we think it's the combination of the OpenTelemetry Collector (for metrics) and Syslog Drains (for logs) that represents a realistic replacement for the Firehose. And experimenting with the OpenTelemetry Collector now helps set us up for a potential long-term future where we could start using the Collector for logs and traces as well.

> Why is the existence of multiple Open Telemetry Collector exporters (the ability to export the data in different formats) promoted as main selling point which will help the metric consumers? IMO this is a positive side effect of using OpenTelemetry.

I assume there's a "not" missing in here somewhere, which I hope is in the first sentence 😁. I do think that the existence of many OpenTelemetry exporters is a strong reason to include it, and if we can rephrase something in our solution statement to better encapsulate that please let me know what you'd change.

> I think that it would be better instead of hooking the receiver to the metrics-agent, that we build a custom receiver which will be connected directly to the forwarder agent and have application and platform component metrics and application logs at hand... There are some planed changes to the metrics-agent. We should be careful, not to break anything and stay backward compatible.

We think so too! Utilizing the Metrics Agent was our preferred approach initially because it seemed faster. We wouldn't have to build OTLP functionality into Forwarder Agent, or a loggregator envelope receiver into the OpenTelemetry Collector. However, we've actually been backtracking on that approach in favor of one of the other two options already, so we're open to reevaluating the steel thread of the proposal to not include Metrics Agent at all.

I'll call out that we explored the codebase and couldn't find a reason for why the Metrics Agent doesn't serve all metrics on the `/metrics` endpoint, and our thinking was that might have been an oversight that was never recognized due to lack of use of the component.

**Review by chombium — APPROVED** [review]

**Comment by beyhan** [comment]
Final period for comment ends 25th of July.

**Comment by chombium** [comment]
@ctlong I have few questions regarding the internal Syslog aggregate drain to Log Cache which we have at the moment: 
 - At the moment Log Cache consumes the app logs, application container metrics and platform component metrics via a Syslog aggregate drain. 
 - The aggregate drains are defined in the cf-deployment 
 
As we want to enable more different options to consume the metrics (and eventually logs) in short term and improve the CF's observability in long term on one hand, and on the other hand, we want to provide the Syslog Drain + OTel Collector combination as an alternative to the Firehose, what would happen with the internal Syslog drain to Log Cache when we activate the OpenTelemetry Collector? Will this change affect the aggregate Syslog drains in any way? 

I assume the newly planned OTel Collector targets only external metrics (and later logs) consumers, right?

How will the CF users configure the new metric aggregate egress with OTel Collector?

**Comment by ctlong** [comment]
@acrmp and I just updated the RFC to remove Metrics Agent changes, for reasons discussed in previous comments. Instead the Forwarder Agent can be altered in a backwards compatible way to forward metrics to the OTel Collector.

**Review by stephanme — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Comment by beyhan** [comment]
For the records:
The FCP ended on 25th of July 2023. During the TOC meeting on that day we agreed that there are no open discussions in this RFC and it can be approved. Additionally, we decided that the introduced change described in [this comment](https://github.com/cloudfoundry/community/pull/641#issuecomment-1648599488) during the FCP period doesn't have such an impact that we should exend the FCP period. Additionally, it was even mentioned as option in the initial version of this RFC.

**Pull request merged**
