### PR TITLE
Add samze to reviewer of CAPI

### PR DESCRIPTION
**Pull request by Samze**
👋 Back working on CloudFoundry and CAPI at Broadcom, looking at eventually becoming an approver. It's been awhile... but I was previously a contributor:
- https://github.com/cloudfoundry/cloud_controller_ng/commits?author=Samze

### CODE REVIEW

**Review by tcdowney — APPROVED** [review]
+1 I worked with Sam on Cloud Controller related features in the past. Glad to see him back. 🙂

**Comment by beyhan** [comment]
Technically we require another thumps up or approval from the CAPI approvers and then we are good to go.

**Comment by Gerg** [comment]
@cloudfoundry/wg-app-runtime-interfaces-capi-approvers please review

**Review by moleske — APPROVED** [review]

**Review by philippthun — APPROVED** [review]

**Review by stephanme — APPROVED** [review]

**Comment by stephanme** [comment]
The Reviewer requirements are met. Welcome @Samze as reviewer in the CAPI area of ARI WG.

**Pull request merged**
