### PR TITLE
[ARI] Add Alex Rocha as capi approver

### PR DESCRIPTION
**Pull request by xandroc**
contributions gist
https://gist.github.com/xandroc/d314de65108f144a2833411d05fbe93a

PR's:
https://github.com/cloudfoundry/cloud_controller_ng/pull/3925
https://github.com/cloudfoundry/cloud_controller_ng/pull/3894
https://github.com/cloudfoundry/cloud_controller_ng/pull/3745
https://github.com/cloudfoundry/cloud_controller_ng/pull/2837
https://github.com/cloudfoundry/cloud_controller_ng/pull/2807
https://github.com/cloudfoundry/cloud_controller_ng/pull/2803/
https://github.com/cloudfoundry/capi-release/pull/454
https://github.com/cloudfoundry/capi-release/pull/444
https://github.com/cloudfoundry/capi-release/pull/295
https://github.com/cloudfoundry/capi-release/pull/248
https://github.com/cloudfoundry/docs-running-cf/pull/121

https://github.com/pivotal-cf/docs-partials/pull/194
https://github.com/cloudfoundry/capi-bara-tests/pull/101
https://github.com/cloudfoundry/capi-bara-tests/pull/102
https://github.com/cloudfoundry/cloud_controller_ng/pull/3928
https://github.com/cloudfoundry/cloud_controller_ng/pull/3892

### CODE REVIEW

**Comment by Gerg** [comment]
Per https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver, you need 2 existing CAPI approvers to review the application to affirm that you meet the criteria for promotion. Once the review is complete, Stephan or I can merge this PR.

cc @cloudfoundry/wg-app-runtime-interfaces-capi-approvers

**Review by Benjamintf1 — APPROVED** [review]

**Review by tcdowney — APPROVED** [review]
Sounds good to me!

**Review by moleske — APPROVED** [review]
Finally! 😉 

Thrilled to have you continue contributing!

**Review by Gerg — APPROVED** [review]
Congrats on your promotion!

**Pull request merged**
