### PR TITLE
Move Prateek Gangwal to UAA and Credhub approver.

### PR DESCRIPTION
**Pull request by coolgang123**
Credential Management (Credhub) and Identity and Auth (UAA) contributions

Reviews:

feat: Return a sorted IdP list- https://github.com/cloudfoundry/uaa/pull/2980
fix: replace regex usage with simple search- https://github.com/cloudfoundry/uaa/pull/2866
Fix documentation for OpenID connect clientJWT: https://github.com/cloudfoundry/uaa/pull/2937
fix: api docs build failure: https://github.com/cloudfoundry/credhub/pull/751

Code Contributions:

bump: Gradle version to the latest - https://github.com/cloudfoundry/credhub/pull/757
Update kotlin to 2.0.0 - https://github.com/cloudfoundry/credhub/pull/743
Enable configuring of cache for Identity providers in UAA - https://github.com/cloudfoundry/uaa-release/pull/906 
Identity provider key caching behavior causing lookup conflict- https://github.com/cloudfoundry/uaa/pull/2915

### CODE REVIEW

**Review by Tallicia — APPROVED** [review]
This looks good and will help the team's efficiency!

**Review by duanemay — APPROVED** [review]

**Review by jpalermo — APPROVED** [review]
👍

**Comment by beyhan** [comment]
Contributions generated with the [contributions-for-user.sh](https://github.com/cloudfoundry/community/blob/main/toc/working-groups/contributions-for-user.sh) script.

# Foundational Infrastructure: Identity and Auth (UAA) Contributions
### PRs Commented on/Reviewed:
- 2024-05-03T10:27:18Z: [fix: replace regex usage with simple search](https://github.com/cloudfoundry/uaa/pull/2866)
- 2024-06-11T21:22:50Z: [Enable configuring of cache for Identity providers in UAA](https://github.com/cloudfoundry/uaa-release/pull/906)
- 2024-06-19T14:23:11Z: [Fix documentation for OpenID connect clientJWT](https://github.com/cloudfoundry/uaa/pull/2937)
- 2024-07-24T12:11:41Z: [Bump chromedriver from 126.0.5 to 127.0.0](https://github.com/cloudfoundry/uaa-singular/pull/514)
- 2024-07-27T08:10:14Z: [feat: Return a sorted IdP list](https://github.com/cloudfoundry/uaa/pull/2980)
- 2024-07-29T11:20:22Z: [Bump nokogiri from 1.16.6 to 1.16.7](https://github.com/cloudfoundry/uaa-release/pull/927)
- 2024-07-29T11:41:20Z: [Bump nokogiri from 1.16.6 to 1.16.7](https://github.com/cloudfoundry/uaa-release/pull/928)
- 2024-07-29T12:01:31Z: [Bump github.com/cloudfoundry/bosh-utils from 0.0.479 to 0.0.480 in /src/acceptance_tests](https://github.com/cloudfoundry/uaa-release/pull/929)
- 2024-07-31T08:55:34Z: [Optional BC-FIPS upgrade to 2.0.0](https://github.com/cloudfoundry/uaa/pull/2987)
- 2024-07-31T11:47:21Z: [Bump chromedriver from 127.0.0 to 127.0.1](https://github.com/cloudfoundry/uaa-singular/pull/515)
### Issues that may be relevant:
- 2024-06-04T21:07:14Z: [Identity provider key caching behavior causing lookup conflict](https://github.com/cloudfoundry/uaa/pull/2915)
- 2024-06-11T21:22:50Z: [Enable configuring of cache for Identity providers in UAA](https://github.com/cloudfoundry/uaa-release/pull/906)
- 2024-07-29T12:01:31Z: [Bump github.com/cloudfoundry/bosh-utils from 0.0.479 to 0.0.480 in /src/acceptance_tests](https://github.com/cloudfoundry/uaa-release/pull/929)
- 2024-07-30T11:34:50Z: [build(deps): bump org.bouncycastle:bcpkix-fips from 1.0.7 to 2.0.7](https://github.com/cloudfoundry/uaa/pull/2985)
- 2024-07-30T11:35:18Z: [build(deps): bump org.bouncycastle:bc-fips from 1.0.2.5 to 2.0.0](https://github.com/cloudfoundry/uaa/pull/2986)
### Code contributions:
- 2024-06-12T16:34:26Z: [A new oidc provider config "cacheJwks" is added (#906)](https://github.com/cloudfoundry/uaa-release/commit/3ed8df30070f9a4ed8ae71a4e4f98628910d2bd7)

# Foundational Infrastructure: Credential Management (Credhub) Contributions
### PRs Commented on/Reviewed:
- 2024-07-26T12:01:16Z: [build(deps): bump com.google.api.grpc:proto-google-common-protos from 2.41.0 to 2.42.0](https://github.com/cloudfoundry/credhub/pull/767)
### Issues that may be relevant:
- 2024-05-23T18:00:54Z: [Update kotlin to 2.0.0](https://github.com/cloudfoundry/credhub/pull/743)
- 2024-06-18T21:44:05Z: [fix: api docs build failure](https://github.com/cloudfoundry/credhub/pull/751)
- 2024-07-03T21:22:19Z: [bump: Gradle version to the latest](https://github.com/cloudfoundry/credhub/pull/757)
- 2024-07-30T11:19:47Z: [build(deps): bump org.bouncycastle:bc-fips from 1.0.2.5 to 2.0.0](https://github.com/cloudfoundry/credhub/pull/768)
- 2024-07-30T11:20:04Z: [build(deps): bump org.bouncycastle:bcpkix-fips from 1.0.7 to 2.0.7](https://github.com/cloudfoundry/credhub/pull/769)
### Code contributions:
- 2024-07-03T20:17:53Z: [Bump Gradle to 8.8](https://github.com/cloudfoundry/credhub/commit/d2164c6648e15e40bb6389e6fb2aa506f86f3bfd)

**Review by beyhan — APPROVED** [review]

**Comment by beyhan** [comment]
Congratulations @coolgang123!

**Pull request merged**
