### PR TITLE
[WIP] Add branch protection for FI WG repos

### PR DESCRIPTION
**Pull request by beyhan**
This is pr is to start the discussion in the FI WG about introducing branch protection rules for all repositories. We should make sure that the recommendation for branch protections are in place:
- [ ] Replace github deploy keys by working group bot users. Branch protection rules enforce PRs for commits with deploy keys (enforce_admins=true).
- [ ] Ensure that all bot users are members of the working group bots team or working group area bots team.
- [ ] Remove all direct repository users in 'Settings > Collaborators and teams'. Repository access shall be governed by the generated teams only.
- [ ] exclude repos w/o source code 

cc @rkoster @jpalermo

### CODE REVIEW

**Comment by rkoster** [comment]
I did a quick survey, and 110 (out of 240) repos in the foundational infrastructure working group use deployment keys.

```
./toc/working-groups/parsable-working-groups.sh | jq -s -r 'map(map(select(.name == "Foundational Infrastructure"))[0].areas)' | bosh int - | grep cloudfoundry | cut -d'/' -f2 > repos
for repo in $(cat repos); do; echo "cloudfoundry/${repo}: $(gh api https://api.github.com/repos/cloudfoundry/${repo}/keys | jq -r '.[].last_used')"; done > results
cat results | grep Z | grep '/' | wc -l
 ```

**Comment by jpalermo** [comment]
Can't say I'm thrilled about replacing 110 fine grained access keys with 1 access key that has access to everything, but maybe we can use the centralization of they credentials as an opportunity to add automatic rotation of the keys on the bot users.

**Comment by rkoster** [comment]
Personal access tokens can still be fine grained: https://github.blog/2022-10-18-introducing-fine-grained-personal-access-tokens-for-github/

**Comment by jpalermo** [comment]
👍 right, I remember having this conversation now 😀

**Comment by beyhan** [comment]
Closing for now. We will reopen when we plan to work on this.

**Pull request closed without merging**
