### PR TITLE
Archive old Diego CI repos

### PR DESCRIPTION
**Pull request by ebroberson**
Signed-off-by: Brandon Roberson <broberson@vmware.com>
Co-authored-by: Brandon Roberson <broberson@vmware.com>

### CODE REVIEW

**Comment by emalm** [comment]
Thanks, @ebroberson ! Would you mind also updating https://github.com/cloudfoundry/community/blob/main/org/cloudfoundry.yml to add `archived: true` entries under the `deployments-diego` and `diego-ci` keys in `orgs.cloudfoundry.repos`? With that change to this PR, the repository automation will automatically archive those two repos after this PR is merged.

**Review by emalm — CHANGES_REQUESTED** [review]
@ebroberson @winkingturtle-vmw bump in regard to adding `archived: true` attributes to these repos in https://github.com/cloudfoundry/community/blob/main/org/cloudfoundry.yml.

**Comment by ebroberson** [comment]
@emalm Sorry for the delay on that!

**Review by emalm — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Review by stephanme — APPROVED** [review]

**Comment by ebroberson** [comment]
@christopherclark @emalm I've updated EasyCLA so the bot can be kicked.

**Comment by emalm** [comment]
@christopherclark Is closing and re-opening the PR the best procedure to get the EasyCLA check to re-run, or is there some other process to follow?

**Comment by emalm** [comment]
@ctlong would you be able to sign off on this repo change in a comment in Amelia's stead? (It can't be a formal review because your role doesn't grant you sufficient access on the community repo.) Thanks!

**Comment by geofffranks** [comment]
@emalm If you'll accept my approval, i'll sign off on this in Amelia's stead.

**Review by ctlong — APPROVED** [review]

**Pull request merged**
