### PR TITLE
Promote klaus-sap to UAA approver

### PR DESCRIPTION
**Pull request by klaus-sap**

### CODE REVIEW

**Comment by beyhan** [comment]
According to the the [Promotion to Reviewer or Approver](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver) we need two approvals. It will be good if we could get an approval from different involved parties.

**Comment by beyhan** [comment]
ping @peterhaochen47, @bruce-ricard, @swalchemist, @Tallicia

**Review by swalchemist — APPROVED** [review]

**Review by Tallicia — APPROVED** [review]
Looks good

**Comment by beyhan** [comment]
Thanks and welcome as reviewer @klaus-sap.

**Review by beyhan — APPROVED** [review]

**Pull request merged**
