### PR TITLE
add cloudfoundry/healthchecker to ARP WG

### PR DESCRIPTION
**Pull request by ameowlia**
This is for my WG and I approve 🎉

### CODE REVIEW

**Review by dsboulder — APPROVED** [review]

**Review by dsboulder — APPROVED** [review]

**Comment by dsboulder** [comment]
@emalm could you approve this for us?

**Comment by emalm** [comment]
@ameowlia @dsboulder What's the new repo for?  /cc @cloudfoundry/toc

**Comment by ameowlia** [comment]
It is a healthchecker that restarts bosh jobs when HTTP endpoints stop responding. The monit including in CF is so old that it can't do HTTP checks, so this is an alternative for that. This code currently exists in [cf-networking-helpers](https://github.com/cloudfoundry/cf-networking-helpers/blob/main/healthchecker/cmd/healthchecker/main.go), but we want it to graduate into its own repo. It is currently used for gorouter, silk-controller, garden, and others.

**Comment by emalm** [comment]
Thanks, @ameowlia! Sounds good to me. If this proves useful outside of its current ARP usage, maybe it's a utility that the Foundational Infrastructure WG should own in the long term.

**Review by emalm — APPROVED** [review]

**Review by stephanme — APPROVED** [review]

**Review by beyhan — APPROVED** [review]

**Pull request merged**
