### PR TITLE
[ARP] working agreement: making working agreements

### PR DESCRIPTION
**Pull request by ameowlia**
Please leave this PR open until the ARP working group discusses and votes.

### CODE REVIEW

**Comment by beyhan** [comment]
+1

**Comment by ameowlia** [comment]
😅 @beyhan  - I appreciate your enthusiasm to vote, but you are not an approver in the App Runtime Platform working group, and thus ineligible to vote for our working agreements. Though you are welcome to join!

**Comment by geofffranks** [comment]
+1

**Comment by beyhan** [comment]
> 😅 @beyhan - I appreciate your enthusiasm to vote, but you are not an approver in the App Runtime Platform working group, and thus ineligible to vote for our working agreements. Though you are welcome to join our WG if you want!

@ameowlia I though that we are going for global working agreements and didn't notice that this is for the App Runtime Platform WG. Sorry, for spamming the approval process :-)

**Comment by ctlong** [comment]
+1

**Comment by Gerg** [comment]
+1

**Comment by IvanHristov98** [comment]
+1

**Comment by ameowlia** [comment]
6 vote for and 0 against. Accepted!

**Review by geofffranks — APPROVED** [review]

**Review by dsboulder — APPROVED** [review]

**Pull request merged**
