### PR TITLE
Add Stefan Yonkov as reviewer

### PR DESCRIPTION
**Pull request by s-yonkov-yonkov**

### CODE REVIEW

**Review by theghost5800 — APPROVED** [review]
Stefan Yonkov is a new team member of multiapps team

**Review by boyan-velinov — APPROVED** [review]

**Review by boyan-velinov — APPROVED** [review]
Stefan Yonkov is a new team member of multiapps team

**Comment by beyhan** [comment]
contributions were listed in https://github.com/cloudfoundry/community/pull/794#issuecomment-2017726400

**Review by stephanme — APPROVED** [review]

**Comment by stephanme** [comment]
Welcome to the ARI working group.

**Pull request merged**
