### PR TITLE
[ARI] Add Lokowandtg as reviewer for Java Tools

### PR DESCRIPTION
**Pull request by Lokowandtg**
I would like to contribute to cf-java-client

### CODE REVIEW

**Comment by Gerg** [comment]
In order to be a WG Reviewer, you need to be a CFF Contributor (basically, you need to be in [contributors.yml](https://github.com/cloudfoundry/community/blob/main/org/contributors.yml)).

The Contributor and Reviewer promotion process is described here: https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-contributor

Feel free to add their Contributor promotion into this PR.

**Review by Gerg — CHANGES_REQUESTED** [review]
In order to be a WG Reviewer, you need to be a CFF Contributor (basically, you need to be in [contributors.yml](https://github.com/cloudfoundry/community/blob/main/org/contributors.yml)).

The Contributor and Reviewer promotion process is described here: https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-contributor

Feel free to add their Contributor promotion into this PR.

**Comment by Lokowandtg** [comment]
Adding [pull request](https://github.com/cloudfoundry/community/pull/1027) to become a contributor...

**Comment by anthonydahanne** [comment]
hello, I reviewed and I approve!
Welcome @Lokowandtg !

**Review by Gerg — APPROVED** [review]

**Pull request merged**
