### PR TITLE
Add more Garden repos

### PR DESCRIPTION
**Pull request by selzoc**
We recently transferred several Garden-related repositories from the https://github.com/masters-of-cats/ org.

### CODE REVIEW

**Comment by stephanme** [comment]
The PR needs to be rebased and adapted to the new yaml format.

**Comment by selzoc** [comment]
Rebased and yaml'd - thanks!

**Review by stephanme — APPROVED** [review]

**Review by rkoster — APPROVED** [review]

**Comment by emalm** [comment]
@ameowlia this has TOC approval now. Can you also approve? Thanks!

**Comment by emalm** [comment]
@ctlong @Benjamintf1 Could you please review this PR and approve in Amelia's stead if it seems good to you? The TOC has already approved adding these repos to the WG.

**Review by Benjamintf1 — APPROVED** [review]
lgtm

**Comment by Benjamintf1** [comment]
I can't say I entirely am familiar with these repos, but nothing seems glaringly wrong or like it'd be a problem.

**Comment by emalm** [comment]
Resolved a merge conflict. No change in substance, so I'm merging this!

**Pull request merged**
