### PR TITLE
Add Klaus to UAA

### PR DESCRIPTION
**Pull request by strehle**
Please add https://github.com/klaus-sap

He will participate in UAA contributes, he did some PR in the past

https://github.com/search?q=repo%3Acloudfoundry%2Fuaa+klaus-sap&type=pullrequests

### CODE REVIEW

**Comment by strehle** [comment]
FYI @cloudfoundry/wg-foundational-infrastructure-identity-and-auth-uaa-approvers

**Review by tack-sap — APPROVED** [review]

**Comment by beyhan** [comment]
According to the [Promotion to Reviewer or Approver](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver) rules this pr needs to be approved by two approves.

**Comment by strehle** [comment]
@beyhan Approved

**Review by torsten-sap — APPROVED** [review]

**Review by beyhan — CHANGES_REQUESTED** [review]
Klaus doesn't seem to be a contributor yet. Could you please also add him the the https://github.com/cloudfoundry/community/blob/main/org/contributors.yml.

**Review by beyhan — APPROVED** [review]

**Review by Tallicia — APPROVED** [review]
Approved by me as well

**Review by rkoster — APPROVED** [review]

**Pull request merged**
