### PR TITLE
[ARI] Add Yavor16 to app-runtime-interfaces.md

### PR DESCRIPTION
**Pull request by Yavor16**

### CODE REVIEW

**Comment by Yavor16** [comment]
Hi @beyhan,
I added the change here
Best regards,
Yavor

**Review by VRBogdanov — APPROVED** [review]
Yavor16 is a new team member of multiapps team

**Comment by Gerg** [comment]
Per https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver, you need 2 existing MultiApps approvers to review your application and affirm that you meet the requirements for approver. Once the review is complete, I can merge this PR.

**Review by boyan-velinov — APPROVED** [review]
Yavor Uzunov is our new team member

**Review by Gerg — APPROVED** [review]
Welcome!

**Pull request merged**
