### PR TITLE
Add VRBogdanov as contributor

### PR DESCRIPTION
**Pull request by VRBogdanov**
Started contributing to [multiapps-controller](https://github.com/VRBogdanov/multiapps-controller) and [multiapps](https://github.com/VRBogdanov/multiapps)

### CODE REVIEW

**Review by radito3 — APPROVED** [review]

**Review by boyan-velinov — APPROVED** [review]
VRBogdanov is new team member of multiapps team

**Review by theghost5800 — APPROVED** [review]

**Comment by Gerg** [comment]
I'm happy to add you as a [Contributor](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#contributor).

To be promoted to the Approver role, you need to meet [certain criteria](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#approver). The promotion process is [described here](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-and-revocation).

**Comment by beyhan** [comment]
According to the [promotion process](https://github.com/cloudfoundry/community/blob/main/toc/ROLES.md#promotion-to-reviewer-or-approver) we have enough approvers and this could be merged by the WG lead.

**Review by Gerg — APPROVED** [review]
Welcome!

**Pull request merged**
