### PR TITLE
Add stub template for Community Experience WG

### PR DESCRIPTION
**Pull request by emalm**
TODO before merge:
* Identify leads for WG
* Identify initial goals and scope for WG
* List main technical assets for WG

This PR supersedes #144: the content is identical, but it pulls from the `wg-community-experience` branch on the CF-org community repo instead of the one on my personal fork so that the other TOC members can revise it.

### CODE REVIEW

**Comment by emalm** [comment]
As an alternative to forming this working group, we could instead put the existing docs repos under the governance of the most relevant technical working group. The Foundational Infrastructure WG has already done this with most of the docs repos for BOSH and CredHub (namely, [docs-bbr](https://github.com/cloudfoundry/docs-bbr), [docs-bosh](https://github.com/cloudfoundry/docs-bosh), and [docs-credhub](https://github.com/cloudfoundry/docs-credhub)), and the App Runtime Interfaces WG has also done this for [docs-buildpacks](https://github.com/cloudfoundry/docs-buildpacks).

This would require some existing WGs to take on more scope and to add active contributors to these repos (such as @mjgutermuth, @animatedmax, and @jncd) as Approvers to ensure their ongoing access, likely in a new area of the WG.

Here's my pass at how the remaining docs repos would get placed within the current WGs:

| Repo | Site | Candidate WG | Notes |
|---|---|---|---|
[api-docs](https://github.com/cloudfoundry/api-docs) | [apidocs.cloudfoundry.org](https://apidocs.cloudfoundry.org/) | AR Interfaces
[credhub-api-docs](https://github.com/cloudfoundry-incubator/credhub-api-docs) | [docs.cloudfoundry.org/api/credhub](https://docs.cloudfoundry.org/api/credhub/) | Foundational Infrastructure | Move from cf-incubator org
[cf-for-k8s-docs](https://github.com/cloudfoundry/cf-for-k8s-docs) | [cf-for-k8s.io](https://cf-for-k8s.io/) | None | Archive as not maintained
[docs-book-cloudfoundry](https://github.com/cloudfoundry/docs-book-cloudfoundry) | [docs.cloudfoundry.org](https://docs.cloudfoundry.org/) | AR Platform |
[docs-cf-admin](https://github.com/cloudfoundry/docs-cf-admin) | [docs.cloudfoundry.org/adminguide](https://docs.cloudfoundry.org/adminguide/) | AR Platform
[docs-cf-cli](https://github.com/cloudfoundry/docs-cf-cli) | [docs.cloudfoundry.org/cf-cli](https://docs.cloudfoundry.org/cf-cli/) | AR Interfaces
[docs-cfcr](https://github.com/cloudfoundry/docs-cfcr) | [docs.cloudfoundry.org/cfcr](https://docs.cloudfoundry.org/cfcr/) | None | Archive as not maintained
[docs-cloudfoundry-concepts](https://github.com/cloudfoundry/docs-cloudfoundry-concepts) | [docs.cloudfoundry.org/concepts](https://docs.cloudfoundry.org/concepts/) | AR Interfaces
[docs-dev-guide](https://github.com/cloudfoundry/docs-dev-guide) | [docs.cloudfoundry.org/devguide](https://docs.cloudfoundry.org/devguide/) | AR Interfaces
[docs-dotnet-core-tutorial](https://github.com/cloudfoundry/docs-dotnet-core-tutorial) | None? | None | Archive as not maintained
[docs-loggregator](https://github.com/cloudfoundry/docs-loggregator) | [docs.cloudfoundry.org/loggregator/architecture.html](https://docs.cloudfoundry.org/loggregator/architecture.html) | AR Platform
[docs-routing](https://github.com/cloudfoundry/docs-routing) | None | None | Archive as obsolete
[docs-running-cf](https://github.com/cloudfoundry/docs-running-cf) | [docs.cloudfoundry.org/running](https://docs.cloudfoundry.org/running/) | AR Platform
[docs-services](https://github.com/cloudfoundry/docs-services) | [docs.cloudfoundry.org/services](https://docs.cloudfoundry.org/services/) | AR Interfaces
[docs-uaa](https://github.com/cloudfoundry/docs-uaa) | [docs.cloudfoundry.org/uaa](https://docs.cloudfoundry.org/uaa/) | Foundational Infrastructure

@rkoster @beyhan @ameowlia @Gerg, as the leads for the WGs that would take on these docs repos, could you please provide feedback on this proposal? Thanks!

**Comment by emalm** [comment]
@Gerg @ameowlia: I'd still like your feedback on [the proposal above](https://github.com/cloudfoundry/community/pull/150#issuecomment-993419174) to move some CF docs repos into the scope of your working groups. Thanks!

**Comment by Gerg** [comment]
As it currently stands, most of the docs.cloudfoundry.org/* repos are managed by a different set of people than are currently in the existing working groups. I think it makes sense to have a Community Experience WG to reflect this current reality. If we want to transition to a model where these docs are maintained by the other WGs, then we can do that as its own initiative.

That said, there are some (generally API) docs that are maintained by existing WG teams:
- https://apidocs.cloudfoundry.org
- https://v3-apidocs.cloudfoundry.org/
- https://cli.cloudfoundry.org/en-US/v8/
- https://docs.cloudfoundry.org/api/uaa
- etc

I think it makes sense for those to fall into the associated WG. Of the repos you listed, I think this only applies to https://github.com/cloudfoundry/api-docs.

**Comment by Gerg** [comment]
I had a follow up discussion with Eric. There probably aren't enough people currently contributing to the docs repos to support an entire working group. As an alternative, we can add a "Documentation" (or Community Experience") team to each of the existing working groups.

**Comment by ameowlia** [comment]
I like @Gerg's alternative mentioned above. I wish there was enough contributors to justify a docs working group, but here we are. @emalm your mapping of docs to WG makes sense for ARP.

**Comment by emalm** [comment]
@Gerg @ameowlia Thank you both! Generated https://github.com/cloudfoundry/community/pull/190 to propose these additions to the existing working groups. I will close this PR as obsolete now, and we can proceed from the new one.

**Pull request closed without merging**
