### PR TITLE
working-groups/buildpacks: Add private repos, remove one

### PR DESCRIPTION
**Pull request by arjun024**
- Add 2 buildpacks team private repos
- ~Remove `buildpackapplifecycle` which should be part of Platform/Diego area~
- Move `buildpackapplifecycle` to Platform/Diego area

### CODE REVIEW

**Comment by arjun024** [comment]
cc @brayanhenao @ryanmoran @dmikusa-pivotal @pivotal-david-osullivan

**Review by brayanhenao — APPROVED** [review]

**Review by ryanmoran — APPROVED** [review]

**Comment by Gerg** [comment]
@arjun024 can you update this PR to add `cloudfoundry/buildpackapplifecycle` to [the ARP charter](https://github.com/cloudfoundry/community/blob/e91611ab94c854927271fe28908a33373077d138/toc/working-groups/app-runtime-platform.md?plain=1#L61)?

That way we can sort this out in a single PR.

**Comment by arjun024** [comment]
@Gerg Done

**Review by Gerg — APPROVED** [review]

**Review by stephanme — APPROVED** [review]

**Review by AP-Hunt — APPROVED** [review]

**Review by ctlong — APPROVED** [review]
LGTM

**Pull request merged**
