### PR TITLE
Add new team member Pete Levine

### PR DESCRIPTION
**Pull request by reedr3**
Add new team member Pete Levine (github username PeteLevineA) to CF CLI and PCF Apps Manager.

### CODE REVIEW

**Review by PeteLevineA — APPROVED** [review]
LGTM

**Review by jdgonzaleza — APPROVED** [review]
LGTM

**Comment by jdgonzaleza** [comment]
@reedr3 could we delete dominic and sarah from the appsManager section as they are not working the proyect anymore?

**Review by Gerg — APPROVED** [review]

**Comment by PeteLevineA** [comment]
@Gerg would you mind merging this for us? Doesn't appear like anyone on my team has perms to do so

**Pull request merged**
