### PR TITLE
Promote mkocher to ARP WG Logging & Metrics approver

### PR DESCRIPTION
**Pull request by mkocher**
I'd like to be added as an approver in the Logging & Metrics working group. 

@ameowlia would you be willing to nominate me?

Significant PR's Authored:

- https://github.com/cloudfoundry/loggregator-agent-release/pull/108
- https://github.com/cloudfoundry/log-cache-release/pull/75
- https://github.com/cloudfoundry/system-metrics-release/pull/8
- https://github.com/cloudfoundry/log-cache-release/pull/61
- https://github.com/cloudfoundry/bosh-system-metrics-forwarder-release/pull/8
- https://github.com/cloudfoundry/log-cache-release/pull/57
- https://github.com/cloudfoundry/cf-deployment/pull/949
- https://github.com/cloudfoundry/go-log-cache/pull/32
- https://github.com/cloudfoundry/cf-deployment/pull/959

Reviewed:
- https://github.com/cloudfoundry/loggregator-agent-release/pull/92
- https://github.com/cloudfoundry/loggregator-agent-release/pull/90
- https://github.com/cloudfoundry/log-cache-release/pull/60
- https://github.com/cloudfoundry/log-cache-release/pull/59
- https://github.com/cloudfoundry/metrics-discovery-release/pull/24
- https://github.com/cloudfoundry/loggregator-agent-release/pull/88
- https://github.com/cloudfoundry/loggregator-agent-release/pull/82
- https://github.com/pivotal-cf/metric-registrar-cli/pull/13
- https://github.com/pivotal-cf/metric-registrar-release/pull/14
- https://github.com/pivotal-cf/metric-registrar-release/pull/16
- https://github.com/cloudfoundry/log-cache-release/pull/55
- https://github.com/cloudfoundry/log-cache-release/pull/56
- https://github.com/cloudfoundry/system-metrics-scraper-release/pull/7
- https://github.com/pivotal-cf/metric-registrar-release/pull/12
- https://github.com/cloudfoundry/loggregator-agent-release/pull/77
- https://github.com/cloudfoundry/loggregator-agent-release/pull/79
- https://github.com/cloudfoundry/loggregator-agent-release/pull/78
- https://github.com/cloudfoundry/metrics-discovery-release/pull/15

Significant Slack Threads:
- https://cloudfoundry.slack.com/archives/CUW93AF3M/p1654193387225389

### CODE REVIEW

**Comment by ameowlia** [comment]
📝 According to the [docs](https://github.com/cloudfoundry/community/blob/main/toc/rfc/rfc-0006-approver-requirements.md), to be nominated to approver you must be: "Nominated by a WG lead (with no objections from other leads)."

✨ As the WG lead for this area I heartily endorse this nomination.

👉 Tagging other leads. Please comment if you have any objection. If there are no objections within 1 week, then this PR can be merged. https://github.com/orgs/cloudfoundry/teams/toc, https://github.com/orgs/cloudfoundry/teams/working-group-leads

**Review by ctlong — APPROVED** [review]

**Review by Benjamintf1 — APPROVED** [review]

**Review by ameowlia — CHANGES_REQUESTED** [review]
@mkocher - you no longer need to change the cloudfoundry.yml file. That should happen automatically.

**Comment by mkocher** [comment]
> @mkocher - you no longer need to change the cloudfoundry.yml file. That should happen automatically.

Nice, adding it in two places didn't feel great. Updated the PR.

**Review by emalm — APPROVED** [review]
This has the required approvals from other approvers in the area and has addressed the change requested from the WG lead.

**Pull request merged**
