### PR TITLE
Add nitin to BOSH groups

### PR DESCRIPTION
**Pull request by xtreme-nitin-ravindran**
Hi there,

I have been a contributor on BOSH (~2015-2016) and stemcell (on-going for compliance).
I am now a part of the BOSH team.

Cheers,
Nitin

### CODE REVIEW

**Review by aramprice — APPROVED** [review]

**Review by jpalermo — APPROVED** [review]
👍

**Comment by beyhan** [comment]
For reference the contributions of @xtreme-nitin-ravindran:
# Foundational Infrastructure: VM deployment lifecycle (BOSH) Contributions
### PRs Commented on/Reviewed:
### Issues that may be relevant:
- 2016-08-10T13:22:44Z: [fixes formatting using parted on centOS](https://github.com/cloudfoundry/bosh-agent/pull/86)
- 2016-08-30T16:28:13Z: [Update progressbar version from 0.9.2 to  0.21.0](https://github.com/cloudfoundry/bosh/pull/1421)
- 2017-08-23T22:09:39Z: [Add basic user-add_windows](https://github.com/cloudfoundry/os-conf-release/pull/16)
- 2017-09-14T16:13:04Z: [Update stemcell version to 3445.7 in bosh-dev.yml](https://github.com/cloudfoundry/bosh-deployment/pull/139)
- 2019-05-03T21:52:05Z: [[#165802999] Add missing CIS/STIG audit rules and update auditd.conf](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/91)
- 2019-05-30T23:25:52Z: [Add CIS and STIG audit rules](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/95)
- 2019-09-20T20:29:39Z: [STIG: Enable cron logging](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/103)
- 2019-09-26T22:54:27Z: [CIS: Ensure suspicious packets are logged](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/104)
- 2019-09-27T18:53:18Z: [STIG: pam related hardening rules](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/105)
- 2020-02-28T02:00:47Z: [[#168964744] make rsyslog and logrotate configs consistent](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/110)
- 2020-02-29T02:40:03Z: [[#171553414] add CIS, STIG hardening for ssh](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/pull/111)
- 2020-03-11T18:41:38Z: [[#171751912] lock password if crypted_password is not set](https://github.com/cloudfoundry/os-conf-release/pull/53)
- 2023-03-23T20:36:25Z: [job to add/update windows registry](https://github.com/cloudfoundry/windows-utilities-release/pull/12)
- 2024-04-25T08:16:21Z: [Noble pam_lastlog is deprecated its succesor is pam_lastlog2](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/issues/343)
- 2024-07-09T21:53:18Z: [add missing director roles](https://github.com/cloudfoundry/bosh-google-cpi-release/pull/354)
- 2024-07-10T18:34:20Z: [comment for extra permissions in integration tests](https://github.com/cloudfoundry/bosh-google-cpi-release/pull/355)
### Code contributions:
- 2015-09-22T17:52:10Z: [Bump bosh-agent](https://github.com/cloudfoundry/bosh/commit/80f5c3fa562ef06015a32bfb10547ac535eec939)
- 2015-09-22T18:34:17Z: [Fix failing test due to mocking file directory creation](https://github.com/cloudfoundry/bosh/commit/3da2db9d74115b394f8c1e79b8cfabd9d31d8ea3)
- 2015-10-13T13:56:15Z: [[#104119296] Fix unit and integration tests, and make tests compatible with new 1.5 vendoring](https://github.com/cloudfoundry/bosh-agent/commit/e6918192d8e16a6ecec9c383b6388a3f93840468)
- 2015-10-13T14:39:05Z: [[#104119296] bumping go agent repo](https://github.com/cloudfoundry/bosh/commit/06ee5be2d1f7421c1f3aecc73f2f297b85bd4396)
- 2015-10-15T19:56:18Z: [[#104125746] Director can be deployed with default gateway settings](https://github.com/cloudfoundry/bosh/commit/1a018e75e22ceeaee4869bb01d9b5c795394fb8f)
- 2015-10-20T19:07:21Z: [bump agent](https://github.com/cloudfoundry/bosh/commit/4f5c5b3c548e0e3ac0da1e24aace8f4fee0ad5ff)
- 2015-10-20T19:40:06Z: [allow passwordless sudo for users created for bosh-ssh](https://github.com/cloudfoundry/bosh-agent/commit/3d4418a674220fb2f80b6e71ee478118b4f1d608)
- 2015-10-20T19:40:06Z: [allow passwordless sudo for users created for bosh-ssh](https://github.com/cloudfoundry/bosh-agent/commit/e2e36c98b6fa5135ed138b0a1853522a4f1a360d)
- 2015-10-20T19:52:58Z: [adding bosh_sudoers group to os image](https://github.com/cloudfoundry/bosh/commit/650ef135c85bb8b0e1a51eb5d5a413980de217f9)
- 2015-10-21T13:56:43Z: [bump ubuntu and centos OS image](https://github.com/cloudfoundry/bosh/commit/0b321b288c7e4eb7d760c623dacd0abcbf491cc6)
- 2015-10-21T16:39:47Z: [bump agent](https://github.com/cloudfoundry/bosh/commit/bd4d50e9b0d1cf30634aafe57d8c8ebd31a0934e)
- 2015-10-21T16:41:54Z: [allow passwordless sudo for users created for bosh-ssh](https://github.com/cloudfoundry/bosh/commit/5ad1d9bafb97ec63b555cd14fcc24fc09a837084)
- 2015-10-21T20:03:43Z: [bump agent](https://github.com/cloudfoundry/bosh/commit/69e0088735bd7be671d397606224e4a18a1c7845)
- 2015-10-23T18:06:53Z: [monit should not start any jobs before pre-start is done](https://github.com/cloudfoundry/bosh-agent/commit/68c6a500838448bc238b5678b5020b5e04cf971f)
- 2015-10-23T19:46:15Z: [refactor of monit start](https://github.com/cloudfoundry/bosh-agent/commit/6fe971f89eb98e4836facf696b3b135915ccccd7)
- 2015-10-23T20:36:33Z: [remove agent start error logging for old invalid case](https://github.com/cloudfoundry/bosh/commit/43723195879b1896e3eaf43ba3ca390c837ad23c)
- 2015-10-23T20:39:29Z: [bump agent](https://github.com/cloudfoundry/bosh/commit/e03427a139be38f5a1d370160dfed488d12c0323)
- 2015-10-26T20:57:06Z: [refactored to avoid using @cloud_plugin_is_provided flag](https://github.com/cloudfoundry/bosh/commit/5c0a9fa58d72af65eb7a8b865d6a9d475c23a3ea)
- 2015-10-30T15:27:26Z: [bosh-init raises an error if compiled release does not match given stemcell os / version](https://github.com/cloudfoundry/bosh-cli/commit/66e9417d6c8260af7731e0b0cedc9bab758777fa)
- 2015-10-30T19:39:26Z: [Fix a typo in the stemcell os and version comparison](https://github.com/cloudfoundry/bosh-cli/commit/1b0165e873ae97679a2862710978824e2e31f33f)
- 2015-10-30T19:57:34Z: [Add one more test to check for incorrect stemcell os and versions for compiled releases](https://github.com/cloudfoundry/bosh-cli/commit/d3ded08804622165d3afa55235ea9d469531bfbc)
- 2015-10-30T20:12:30Z: [Make sure that the "extract release" method is called for compiled releases](https://github.com/cloudfoundry/bosh-cli/commit/1e0ad7a1329966663dc1fda493ad30337096626e)
- 2015-10-30T20:20:30Z: [Fix test that makes sure non-cpi compiled releases are being extracted](https://github.com/cloudfoundry/bosh-cli/commit/ed08a00aaa6998ba06ce60a6fd7cd6e1ec0e3784)
- 2015-11-02T14:57:14Z: [bosh-init raises an error if cpi release is compiled](https://github.com/cloudfoundry/bosh-cli/commit/5b9414de3deb872fff0c84839d111eb83b9ed547)
- 2015-11-03T20:35:50Z: [refactor. moved monit status related stuff from start & stop actions to](https://github.com/cloudfoundry/bosh-agent/commit/858ceaa184337e53c40753ff4d4b2793126b09dc)
- 2015-11-03T22:39:39Z: [removed stopped file exist check before it's deletion (in](https://github.com/cloudfoundry/bosh-agent/commit/db74cce1d7844bc167538fe4679a29a40ba35ccb)
- 2015-11-06T15:50:01Z: [- changed root device number detection a bit to be more readable](https://github.com/cloudfoundry/bosh-agent/commit/0fc0213c381d0652a4153aab5e4b75b8907d1ad1)
- 2015-11-06T22:12:11Z: [bosh-init can use non-cpi compiled releases](https://github.com/cloudfoundry/bosh-cli/commit/7ea638dcae29b30f3d12625f0f8e73c1bbed8589)
- 2016-08-10T13:19:25Z: [fixes formatting using parted on centOS](https://github.com/cloudfoundry/bosh-agent/commit/fe8c46c3847d908537e7f989325708c2a0a7d9ae)
- 2016-08-30T16:24:42Z: [Update progressbar version from 0.9.2 to  0.21.0](https://github.com/cloudfoundry/bosh/commit/0fac6e3a84766b149ac262967738cf6bb7a0dd49)
- 2017-09-14T16:12:26Z: [Update stemcell version to 3445.7 in bosh-dev.yml](https://github.com/cloudfoundry/bosh-deployment/commit/d70dde58411fb7f6e561fb6bd86feda50a4861a7)
- 2019-05-03T21:32:26Z: [[#165802999] add missing audit rules](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/d211c996097bacf2dcea36ba12dbdc243f0e71cf)
- 2019-05-30T23:24:31Z: [Add CIS and STIG audit rules](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/2073933a9d050579817ea4b42d071c0b61891a16)
- 2019-09-13T17:54:36Z: [[#168486244] enable cron logging](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/50795884593ca825b04ac11bc16a57cba9a75e92)
- 2019-09-20T20:26:29Z: [clean up stig_spec](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/8c02d0e0d8a7c8561b7d95db6aed8d8d3c171a22)
- 2019-09-26T22:24:43Z: [CIS: Ensure suspicious packets are logged](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/d988ce2af81bf6a5210b45aa0bc8e80174ba039d)
- 2019-09-27T18:45:05Z: [[#168812689] add pam related hardening rules](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/85ab41401c1cd8fc1b3b8b398c3bab63637a3933)
- 2019-09-27T18:45:05Z: [[#168812689] add pam related hardening rules](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/d882c8e61304717734348f9f642c66cce4251b52)
- 2019-09-27T18:46:26Z: [add login.patch](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/656d9afe7e26cd60e6f89daab266026dc4fcb61d)
- 2019-09-27T18:46:26Z: [add login.patch](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/67692d16cb72d30a3bab887da61359e0401b82ae)
- 2019-09-27T18:51:00Z: [[#168812689] add pam related hardening rules](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/d882c8e61304717734348f9f642c66cce4251b52)
- 2019-09-27T18:51:11Z: [add login.patch](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/656d9afe7e26cd60e6f89daab266026dc4fcb61d)
- 2019-10-04T17:20:47Z: [CIS: sync 50-default.conf and logrotate sttings](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/ec0ba310a7f6baaa54e642af43c99f7088bf87fd)
- 2019-10-18T16:18:05Z: [Revert "CIS: sync 50-default.conf and logrotate sttings"](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/8d7cbcd7573be4da0a8ab7cffa0519176b7e8508)
- 2020-02-28T01:57:24Z: [[#168964744] make rsyslog and logrotate configs consistent](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/74171bc1e1ff629173f9e4c6c0fb11dbd3950721)
- 2020-02-29T02:37:50Z: [[#171553414] add CIS, STIG hardening for ssh](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/2744e8d4291e4561173a4580236494fc236e9b8a)
- 2020-03-11T18:22:12Z: [[#171751912] lock password if crypted_password is not set](https://github.com/cloudfoundry/os-conf-release/commit/f9c899e5cb654a9b0f459e0fe245e529a3ebdbce)
- 2023-03-23T20:29:34Z: [job to add/update windows registry](https://github.com/cloudfoundry/windows-utilities-release/commit/711086ae103822a5baf3e7d70d85e052c4220f0b)
- 2024-06-05T22:28:06Z: [Handles EFI stemcells in mount-image helper](https://github.com/cloudfoundry/bosh-linux-stemcell-builder/commit/77e8ca10b0746a3e0032ab7cc22c7ef6f4877f31)
- 2024-06-10T21:16:44Z: [Manully remove jumpbox/director vars stores](https://github.com/cloudfoundry/bosh-bbl-ci-envs/commit/856c955d2805110a99118c961f443b9bbfbfbdf1)
- 2024-07-09T19:48:23Z: [correctly set custom gcp role to be used by int test](https://github.com/cloudfoundry/bosh-google-cpi-release/commit/ebd8d90aa77054619ed083c79672609823d5f445)
- 2024-07-10T18:30:17Z: [comment for extra permissions in integration tests](https://github.com/cloudfoundry/bosh-google-cpi-release/commit/943805b52ad7e603d4287668ebed707a144a2982)
- 2024-07-18T18:59:40Z: [fixup imports](https://github.com/cloudfoundry/stembuild/commit/7df46f6df9121f519e26df90fb24d20b9f473d5b)
- 2024-07-18T19:54:39Z: [Make tests more explicit](https://github.com/cloudfoundry/stembuild/commit/61cf194c535241f68faedc87308ebd3c78bfc17e)
- 2024-07-18T19:55:31Z: [RemoteManager returns errors when closing created shell](https://github.com/cloudfoundry/stembuild/commit/08a8f39d3a47ade86aee6d4b940e53a1edbb585c)

**Review by beyhan — APPROVED** [review]

**Comment by xtreme-nitin-ravindran** [comment]
@beyhan: Done

**Comment by beyhan** [comment]
IIRC @rkoster is on vacation so I'm merging. Welcome back @xtreme-nitin-ravindran  as approver!

**Pull request merged**
